# sets_to_include = ["drc", "tdc", "dsk", "blb", "otj", "mkm", "cmr", "voc", "nec"]
# sets_to_include = ['wc03', 'fmom', 'ons', 'dvd', 'alci', 'phtr', 'cma', 'mznr', 'dft', 'tmom', 'cmb2', 'ptg', 'drk', 'tmh1', 'dtk', 'fjmp', 'tfdn', 'wc02', 'tpr', 'cn2', 'p02', 'dci', 'tc19', 'ph18', 'ptk', 'te01', 'afdn', 'aneo', 'tlci', 'aacr', 'hou', 'dmr', 'tsnc', 'csp', 'm14', 'j25', 'cns', 'dds', 'otj', 'fdmu', 'totj', 'tsr', 'snc', 'fic', 'tmed', 'altc', 'tmkc', 'plst', 'pz2', 'cc2', '10e', 'm13', 'tdag', 'cmr', 'tkhc', 'tjou', 'eve', 'c17', 'tcma', 'ori', 'ddh', 'mbs', 'tsoi', 'w17', 'sok', 'oe01', '9ed', 'tsp', 'togw', 'ywoe', 'm21', 'rex', 'ainr', 'mkm', 'c16', 'tc14', 's99', 'clu', 'dmu', 'dmc', 'nem', 'tpip', 'trna', 'moc', 'tgk2', 'cm2', 'oana', 'hho', 'dsk', 'twar', 'ddl', 'tmma', 'thp1', 'adft', 's00', 'me4', 'tcmr', 'tonc', 'fbro', 'fin', 'tpca', 'tmbs', 'mneo', 'ody', 'tnec', 'scg', 'clb', 'awoe', 'tkhm', 'pls', 'big', 'psdg', 'temn', 'khm', 'ddo', 'dde', 'pip', 'fj22', 'thp2', 'tbro', 'tdtk', 'a25', 'tthb', 'ta25', 'tmh3', 'wc97', 'akhm', 'me3', 'l16', 'm15', 'leg', 'pmic', '7ed', 'akh', 'trix', 'aotj', 'wc01', 'ydsk', 'tdmr', 'ttsr', 'tddi', 'e01', 'mrd', 'twwk', 'tcmm', 'ddt', 'ydmu', 'evg', 'nph', 'tafr', 'lcc', 'ttdm', 'mdmu', 'arn', 'ph20', 'tone', 'inr', 'uds', 'tgk1', 'rix', 'admu', 'yotj', 'ths', 'pf24', 'altr', 'macr', 'eld', 'tdm', 'ulg', 'mh3', 'm11', 'dka', 'tzen', 'neo', 'tm14', 'ph17', 'tblc', 'arc', 'ph22', 'yblb', 'fltr', 'ltc', 'tsb', 'ysnc', 'mm3', 'all', 'cmm', 'mafr', 'fut', 'ybro', 'tdc', 'otc', 'gs1', 'fone', 'j22', 'tvoc', 'hbg', 'j21', 'tdsc', 'chr', 'tugl', 'lci', 'ttdc', 'jmp', 'one', 'tfic', 'tltr', 'tala', 'pssc', 'thb', 'ala', 'tdka', 'gnt', 'tust', 'inv', 'tm11', 'ima', 'mma', 'onc', 'c18', 'mkc', 'kld', 'tdvd', 'sld', 'asnc', 'h17', 'rna', 'troe', '2ed', 'tcn2', 'tund', 'mmh2', 'astx', 'aafr', 'wc98', 'q07', 'tmoc', 'bng', 'unh', 'ncc', 'twoc', 'con', 'dst', 'aznr', 'tdsk', 'gpt', 'tlrw', 'me2', 'ptdmu', 'zen', 'tm19', 'taer', 'brc', 'voc', 'rvr', 'tfin', 'roe', 'pmoa', 'takh', 'tima', 'mone', 'mvow', 'tneo', 'unf', 'ddg', 'lrw', 'tmkm', 'tblb', 'tafc', 'woe', 'wwk', 'ytdm', 'pca', 'tgtc', 'ogw', 'tori', 't10e', 'ddj', 'amh3', 'exo', 'totp', 'mat', 'tbig', 'ffdn', 'tstx', 'afr', 'trex', 'arb', '40k', 't40k', 'ddu', 'tdom', 'gtc', 'aer', 'znr', 'avr', 'tths', 'wth', 'ablb', 'hml', 'ktk', 'nec', '2x2', 'tdmc', 'khc', 'tfth', 'ddf', 'ydft', 'm20', '4ed', 'mid', 'c20', 'c14', 'm3c', '2xm', 'xln', 'ph19', 'rav', 'chk', 'c13', 'mh2', 'ugl', 'tm20', 'fj25', 'tbot', 'frf', 'afc', 'bfz', 'wc00', 'vma', 'mm2', 'tm3c', 'cc1', 'hop', 'tiko', 'tdde', 'twoe', 'amh1', 'aone', 'pcel', 'amid', 'emn', 'ymkm', 'mh1', 'sth', 'tclb', 'dom', 'blc', 'tm15', 'msnc', 'tc20', 'woc', 'amh2', 'iko', 'avow', 'tshm', 'mom', 'ddm', 'tznr', 'amom', '5ed', 'tarb', 'vis', 'me1', 'm12', 'slx', 'mstx', 'blb', 'acmm', 'tktk', 'smh3', 'ylci', 'tgrn', 'pf25', 'mor', 'atq', 'tmid', 'amkm', 'war', 'tbfz', 'ice', 'adsk', 'yone', 'm19', 'c19', 'gvl', 'tunf', 'uma', 'tinr', 'thou', 'fdn', 'ltr', 'tisd', 'prm', 'tbbd', 'ema', 'soi', '5dn', 'tmp', 'opca', 'thp3', 'jvc', 'apc', 'ddi', 't2xm', 'tmh2', 'mclb', 'dgm', 'tcm2', 'vow', 'znc', 'pvan', 'sunf', 'acr', 'tc15', 'teld', 'atdm', 'ddk', 'lgn', 'anb', 'tcns', 'yneo', 'pemn', 'fem', 'gn2', 'tm21', 'ddq', 'f17', 't2x2', 'ust', 'dsc', 'l17', 'ddn', 'txln', 'som', 'bro', 'wc99', 'tdmu', 'fclu', 'm10', 'td2', 'tddt', 'und', 'pcy', 'tkld', 'dis', 'tvow', 'bot', 'mir', 'tuma', 'w16', 'p03', 'rtr', 'tc18', 'mb2', 'bbd', 'mic', 'phel', '8ed', 'tc17', 'ptbro', 'tbth', 'tdft', '6ed', 'tbrc', 'trvr', 'tdrc', 'mbro', 'trtr', 'tema', 'oarc', 'bok', 'tc21', 'gn3', 'usg', 'shm', 'twho', 'ppc1', 'stx', 'c21', 'c15', 'past', 'abro', 'isd', 'mmq', 'plc', 'spe', 'ddr', 'aclb', 'ph21', 'tor', 'f18', 'f12', 'tsom', 'jud', 'totc', 'h2r', 'sum', 'wc04', 'tltc', 'drc', 'ymid', 'mkhm', 'mmid', 'jou', 'cmd', 'who', 'tbng', 'grn', 'ddp', 'tmm3', 'tacr', 'por', 'unk']
sets_to_include = [
    # 2018
    'rix', 'a25', 'dom', 'bbd', 'm19', 'grn', 'uma',
    
    # 2019
    'rna', 'war', 'mh1', 'm20', 'eld',
    
    # 2020
    'thb', 'iko', 'm21', '2xm', 'znr', 'cmr',
    
    # 2021
    'khm', 'tsr', 'stx', 'mh2', 'afr', 'mid', 'vow',
    
    # 2022
    'neo', 'snc', '2x2', 'dmu', 'bro', 'j22',
    
    # 2023
    'one', 'mom', 'mat', 'ltr', 'woe', 'lci',
    
    # 2024
    'rvr', 'mkm', 'otj', 'mh3', 'blb', 'dsk', 'fdn',
    
    # 2025 (released through May 15)
    'inr', 'dft', 'tdm'
]

all_sets = ['tstx', 'tinr', 'mh3', 'prm', 'ulg', 'tddi', 'dis', '7ed', 'mm2', 'eve', 'ttdc', 'dst', 's99', 'pf24', 'scg', 'tfic', 'te01', 'exo', 'ysnc', 'wc02', 'ima', 'tblc', 'mznr', 'tc20', 'tneo', 'tdmu', 'tfth', 'm3c', 'ybro', 'iko', 'pca', 'ths', 'tmoc', 'dsc', 'oana', 'wc04', 'cc2', 'onc', 'ydsk', 'tnec', 'opca', 'bng', 'mom', 'tlci', 'ttsr', 'ltc', 'w17', 'fj25', 'tdmc', 'troe', 'jud', 'woc', 'ainr', 'ncc', 'tcm2', 'tbot', 'leg', 'ktk', 'nem', '9ed', 'mneo', 'dmc', 'tor', 'pmic', 'trna', 'apc', 'pmoa', 'wc99', 'twar', 'ust', 'amh3', 'ywoe', 'oarc', 'cma', 'tala', 'tdmr', 'unk', 'akh', 'aer', 'tddt', 'totj', 'aotj', 'otc', 'aafr', 'tmid', 'thp3', 'rex', 'grn', 'phel', 'amkm', 'arc', 'tuma', 'afc', '2xm', 'atdm', 'jou', 'tsb', 'afr', 'ptg', 'por', 'pip', 'tdvd', 'tvow', 'clu', 'td2', 'cmm', 'mir', 'stx', 'thou', 'fclu', 'lgn', 'fdmu', 'ice', 'anb', 'ydmu', 'drc', 'dgm', '2ed', 'und', 'zen', 'ddq', 'tcns', 'tbfz', 'tund', 'neo', 'avr', 'dft', 'ddh', 'tltr', 'tznr', 'tc19', '5dn', 'admu', '6ed', 'tdc', 'ddk', 'mkm', 'brc', 'nph', 'f12', 'mor', 'dka', 'evg', 'tzen', 'twho', 'fbro', 'wc03', 'tmh2', 'ddn', 'soi', 'moc', 'thb', 'tbrc', 'bro', 'me3', 'bfz', 'm14', 't2x2', 'tmom', 'l17', 'khm', 'f18', 'temn', 'drk', 'tbng', 'phtr', 'hml', 'tm3c', 'tdka', 'one', 'ddf', 'm11', 'ody', 'bot', 'gpt', 'altr', 'tdag', 'tsnc', 'tkhm', 'blc', 'ablb', 'mvow', 'dom', 'fj22', 'tc15', 'avow', 'bok', 't10e', 'cns', 'ph19', 'tpr', 'dmu', 'mh1', 'xln', 'm15', 'tbbd', '8ed', 'hop', 'ddo', 'aclb', '40k', 'tcmm', 'tmkm', 'rix', 'mma', 'gn3', 'hou', 'tmh1', 'eld', 'ddt', 'slx', 'fut', 'hbg', 'mbs', 'ddp', 'mrd', 'tm20', 'tgrn', 'tdsk', 'znr', 'twoe', 'ymkm', 'togw', 'ddl', 'wwk', 'thp1', 'voc', 'ddr', 'tarb', 'mafr', 'tdtk', 'tltc', 'cmr', 'tclb', 'tmh3', 'amid', 'm12', 'alci', 'ddu', 'aacr', 'clb', 'tust', 'emn', 'tkhc', 'ons', 'tblb', 'rtr', 'hho', 'tsoi', 'tiko', 'wc01', 'pz2', 'tths', 'dci', 'dtk', 'chk', 'tbig', 'arn', 'rvr', 'tbth', 'dvd', 'pemn', 'yotj', 'uma', 'tonc', 'fltr', 'adft', 'atq', 'p02', 'cc1', 'tsr', 'a25', 'c18', 'tone', 'c13', 'tdft', 'rna', 'ydft', 'roe', 'cm2', 'dds', 'twoc', 'frf', 'tkld', 'dmr', 'tori', 'rav', 'taer', 'akhm', 'kld', 'c17', 'ala', 'tc14', 'vma', 'ptbro', 'khc', 'w16', 'f17', 'h2r', 'som', 'amh2', 'ddj', 'wth', 'tm21', 'ema', 'ph17', 'ptk', 'tacr', 'ytdm', 'me2', 'csp', 'abro', 'fin', 'mm3', 'twwk', '2x2', 'snc', 'e01', 'mmq', 'sunf', 'pcy', 'j21', 'tc17', 'tthb', 'ddm', 'tmkc', 'totp', 'm19', 'pvan', 'tunf', 'lcc', 'tpip', 'ori', '5ed', 'plst', 'tafr', 'tm15', 'gtc', 'blb', 'ph21', 'arb', 'con', 'unf', 'cmd', 'p03', 'ttdm', 'spe', 'tgk2', 'who', 'q07', 'yneo', 'mat', 'c15', 'ddi', 'me4', 'psdg', 't40k', 'lci', 'tsom', 'ppc1', 'fone', 'sth', 'tpca', 'macr', 'j25', 'tc21', 'tshm', 'aneo', 'asnc', 'totc', 'vis', 'c14', '10e', 'teld', 'ffdn', 'tm14', 'tm19', 'tdrc', 'all', 'mid', '4ed', 'ptdmu', 'znc', 'tdde', 'm13', 'j22', 'tgk1', 'pls', 'woe', 'tdsc', 'trtr', 'mone', 'tdom', 'ymid', 'shm', 'cn2', 'tgtc', 'nec', 'aone', 'mkhm', 'pf25', 'inv', 'oe01', 'ugl', 'fem', 'chr', 'm21', 'tktk', 'tvoc', 'c21', 'tcn2', 'tcma', 'me1', 'fmom', 'l16', 'isd', 'mbro', 'c20', 'war', 'aznr', 'afdn', 'tafc', 'usg', 'c19', 'tmp', 'adsk', 'tsp', 'altc', 'fic', 'lrw', 'tfin', 'acmm', 'dde', 'mb2', 'mdmu', 'amom', 'wc98', 'ylci', 'txln', 'mmid', 'uds', 'sok', 'ta25', 'mstx', 'gn2', 'mmh2', 'tisd', 'dsk', 'mclb', 'ltr', 'pcel', 'tlrw', 'm20', 'trix', 'h17', 'msnc', 'sld', 'wc00', 'jmp', 'unh', 'tima', 'gs1', 'mic', 'jvc', 'bbd', 'ph22', 'amh1', 'm10', 'ddg', 'tmbs', 'smh3', 'tfdn', 'acr', 'tdm', 'mh2', 'tmed', 'fdn', 'big', 'yblb', 'wc97', 'tc18', 'tcmr', 'ph18', 'ph20', 'otj', 't2xm', 'tm11', 'tjou', 'cmb2', 'mkc', 'ogw', 'astx', 'gvl', 'thp2', 'gnt', 'tugl', 'trvr', 'past', 'trex', 'fjmp', 's00', 'yone', 'plc', 'sum', 'takh', 'vow', 'inr', 'tbro', 'awoe', 'tmm3', 'c16', 'tema', 'tmma', 'pssc']



bulk_file = "datasets/bulk/oracle-cards-20250513210734.json"  # Your input file
# bulk_file = "datasets/bulk/oracle-cards-20250514090324.json"


scrapped_store = "datasets/scrapped/store_scrapped.json"
output_scrapped_dir = "datasets/scrapped/"
X_CSRF_Token = "zTErSRYcbvoLCWvThftR9h7SBAaClkXVH-wn5jazcAGX4tlh0MvbvktHr-7d_A-NM6K-L_68uKXzAymcU6UJOA"
cookie = (
    "cf_clearance=_2EOdsOYK.0lTg0KeaSniHX5vocdcKbdqlBoN3WwP6E-1747211339-1.2.1.1-"
    "J82IFA63.45lHJApa0xCTDHGmFnNJl5M2a26oG8_OKRqBtj7LFgmJ5SL2n4dKaue8cRDL7xkx_tTkPTDzZD5Cdsa8zIIAL7LmiqlH8QcxpNZwabcwVab4OPRGgY.hhKDcpmNwdjbVnFIpaSyQpjgN9cLpm2BWLFGaP2vRqDkDITdKyKGXvzM_PXNbt7RrWJizwWDV4nVG85Uxj1zbZTd_wu7rLrprwUFRz8Ta7IdlJTjGjifjtVfyW.foEMCo5DIts68RHrgXIw1e_Xa7IfoIdNsY1MR2Rm8hnX5YCLlzSoTHYUVL1JdU3kTOlwxQ55H5VQ2oXnmt3vKax0VtljqmrLVg.cQOQk57bbwr_TNzEezuuNxKedlcSpnr3csjY..; "
    "auth_token=vBCCIR5nqj8COFOppwSEajmJhJuoD5MV1hjlVacUuLzGvJoLEu6GkA8vZ4zRPxklwG1RiAmYQ7A1rCyeqAO4W2iCRwdEE7WDdApx%2BbBDLqwNPquT1IiuSSS3qq5tg%2FnmsnZ95QpySuy%2F35jQTGEuTsRliZKXn7FuAJc0xgaoqHR6dh9QY9CiHg%3D%3D--n%2FriRWa1kSoxWfHF--1N3fcygpfup0QgUxydH7Kw%3D%3D; "
    "_scryfall_tagger_session=bvI5C3115ver4Qndy8alnT%2Fc1PoD%2FRq9n6xPlHPzAlmgdaMSgWXjdNrAAT1ctNbswtzFY3XkP1xjv6CE5%2BRjyl9edsoxfNKkUw7b6xxUZxT8CaqlsbUQKg5XzZOshWIYSXRZYHu9dqOTI6uYFftTxaT8iDrN0yhd4c7Gdo5g%2BlLJtY7%2FIAVemtxSM0l9dCjT5OyPfRpvP0ZTcLNPgPsnBbRZ81Cbl7deT%2FL9kCVJtA6Go5h2kEJ96oVFc0gxG3ZURqy2K35PXbX%2FvxpDyz1dS2CA8SAglYbXxa3ItMMrz1Q%3D--QogQn4AuIIfzpFXN--nPWq4UiSH%2FRwofOBaBa8NA%3D%3D"
)


processed_json = "datasets/processed/no_indent/commander_legal_cards20250609112722.json"

processed_tag_dir = "datasets/processed/tag_included/"

embedding_file = "datasets/processed/embedding/card_embs_20250515151222.json"

split_dir = "datasets/split/"

MTG_KEYWORDS = {
    "Deathtouch": "Any amount of damage this deals to a creature is enough to destroy it.",
    "Defender": "This creature can't attack.",
    "Double Strike": "This creature deals both first-strike and regular combat damage.",
    "Enchant": "This Aura can only be attached to a specified type of permanent.",
    "Equip": "Attach this Equipment to a creature you control by paying the equip cost.",
    "First Strike": "This creature deals combat damage before creatures without first strike.",
    "Flash": "You may cast this spell any time you could cast an instant.",
    "Flying": "This creature can't be blocked except by creatures with flying or reach.",
    "Haste": "This creature can attack and {T} as soon as it comes under your control.",
    "Hexproof": "This permanent can't be the target of spells or abilities your opponents control.",
    "Indestructible": "Effects that say 'destroy' don't destroy this creature. It can't be destroyed by damage.",
    "Lifelink": "Damage dealt by this creature also causes you to gain that much life.",
    "Menace": "This creature can't be blocked except by two or more creatures.",
    "Prowess": "Whenever you cast a noncreature spell, this creature gets +1/+1 until end of turn.",
    "Reach": "This creature can block creatures with flying.",
    "Trample": "Excess damage this creature deals to blockers is dealt to the defending player or planeswalker.",
    "Vigilance": "Attacking doesn't cause this creature to tap.",
    "Shroud": "This permanent can't be the target of any spells or abilities.",
    "Protection": "This permanent can't be targeted, dealt damage, enchanted, or blocked by anything of the specified quality.",
    "Flashback": "You may cast this card from your graveyard for its flashback cost. Then exile it.",
    "Cycling": "Pay the cycling cost and discard this card to draw a card.",
    "Morph": "You may cast this card face down as a 2/2 creature for {3}. Turn it face up any time for its morph cost.",
    "Persist": "When this creature dies, if it had no -1/-1 counters on it, return it to the battlefield under its owner's control with a -1/-1 counter on it.",
    "Undying": "When this creature dies, if it had no +1/+1 counters on it, return it to the battlefield under its owner's control with a +1/+1 counter on it.",
    "Scry": "Look at the top card(s) of your library, then put any number of them on the bottom of your library and the rest on top in any order.",
    "Cascade": "When you cast this spell, exile cards from the top of your library until you exile a nonland card that costs less. You may cast it without paying its mana cost.",
    "Convoke": "Your creatures can help cast this spell. Each creature you tap while casting this spell pays for {1} or one mana of that creature's color.",
    "Delve": "Each card you exile from your graveyard while casting this spell pays for {1}.",
    "Evoke": "You may cast this spell for its evoke cost. If you do, it's sacrificed when it enters the battlefield.",
    "Kicker": "You may pay an additional cost as you cast this spell to gain an additional effect.",
    "Landwalk": "This creature can't be blocked as long as defending player controls a land of the specified type.",
    "Modular": "This creature enters the battlefield with a number of +1/+1 counters on it. When it dies, you may put its +1/+1 counters on target artifact creature.",
    "Ninjutsu": "Pay the ninjutsu cost and return an unblocked attacker you control to hand: Put this card onto the battlefield from your hand tapped and attacking.",
    "Overload": "You may cast this spell for its overload cost. If you do, change its text by replacing all instances of 'target' with 'each.'",
    "Phasing": "This permanent phases in and out of play, meaning it alternates between being on the battlefield and being treated as though it doesn't exist.",
    "Provoke": "When this creature attacks, you may have target creature defending player controls untap and block it if able.",
    "Rampage": "Whenever this creature becomes blocked, it gets +X/+X until end of turn for each creature blocking it beyond the first.",
    "Rebound": "If you cast this spell from your hand, exile it as it resolves. At the beginning of your next upkeep, you may cast it from exile without paying its mana cost.",
    "Retrace": "You may cast this card from your graveyard by discarding a land card in addition to paying its other costs.",
    "Scavenge": "Exile this card from your graveyard: Put a number of +1/+1 counters equal to this card's power on target creature. Scavenge only as a sorcery.",
    "Split Second": "As long as this spell is on the stack, players can't cast spells or activate abilities that aren't mana abilities.",
    "Storm": "When you cast this spell, copy it for each spell cast before it this turn. You may choose new targets for the copies.",
    "Suspend": "Rather than cast this card from your hand, you may pay its suspend cost and exile it with a number of time counters on it. At the beginning of your upkeep, remove a time counter. When the last is removed, cast it without paying its mana cost.",
    "Transmute": "Pay the transmute cost and discard this card: Search your library for a card with the same converted mana cost, reveal it, and put it into your hand. Then shuffle your library. Transmute only as a sorcery.",
    "Unearth": "Return this card from your graveyard to the battlefield. It gains haste. Exile it at the beginning of the next end step or if it would leave the battlefield. Unearth only as a sorcery.",
    "Wither": "This deals damage to creatures in the form of -1/-1 counters.",
    "Affinity": "This spell costs {1} less to cast for each permanent you control of the specified type.",
    "Annihilator": "Whenever this creature attacks, defending player sacrifices a number of permanents equal to the annihilator number.",
    "Bestow": "If you cast this card for its bestow cost, it's an Aura spell with enchant creature. It becomes a creature again if it's not attached to a creature.",
    "Bloodthirst": "If an opponent was dealt damage this turn, this creature enters the battlefield with additional +1/+1 counters.",
    "Bushido": "When this blocks or becomes blocked, it gets +X/+X until end of turn.",
    "Champion": "When this enters the battlefield, sacrifice it unless you exile another creature you control of the specified type. When this leaves the battlefield, that card returns to the battlefield.",
    "Cipher": "Then you may exile this spell card encoded on a creature you control. Whenever that creature deals combat damage to a player, its controller may cast a copy of the encoded card without paying its mana cost.",
    "Dredge": "If you would draw a card, you may instead put a number of cards from the top of your library into your graveyard and return this card from your graveyard to your hand.",
    "Entwine": "You may choose both modes of a spell with entwine if you pay the entwine cost.",
    "Epic": "For the rest of the game, you can't cast spells. At the beginning of each of your upkeeps, copy this spell except for its epic ability.",
    "Exalted": "Whenever a creature you control attacks alone, that creature gets +1/+1 until end of turn.",
    "Exploit": "When this creature enters the battlefield, you may sacrifice a creature. If you do, it gains an additional effect.",
    "Extort": "Whenever you cast a spell, you may pay {W/B}. If you do, each opponent loses 1 life and you gain that much life.",
    "Fading": "This permanent enters the battlefield with a number of fade counters. At the beginning of your upkeep, remove a fade counter. If you can't, sacrifice it.",
    "Fear": "This creature can't be blocked except by artifact creatures and/or black creatures.",
    "Forecast": "During your upkeep, you may reveal this card from your hand and pay its forecast cost. If you do, an effect occurs.",
    "Graft": "This creature enters the battlefield with a number of +1/+1 counters. Whenever another creature enters the battlefield, you may move a +1/+1 counter from this creature onto it.",
    "Haunt": "When this card is put into a graveyard, exile it haunting target creature. When that creature dies, you may apply an effect.",
    "Hideaway": "This land enters the battlefield tapped. When it does, look at the top four cards of your library, exile one face down, then put the rest on the bottom of your library. You may play the exiled card without paying its mana cost if a certain condition is met.",
    "Infect": "This creature deals damage to creatures in the form of -1/-1 counters and to players in the form of poison counters.",
    "Intimidate": "This creature can't be blocked except by artifact creatures and/or creatures that share a color with it.",
    "Madness": "If you discard this card, you may cast it for its madness cost instead of putting it into your graveyard.",
    "Miracle": "You may cast this card for its miracle cost when you draw it if it's the first card you drew this turn.",
    "Modular": "This creature enters the battlefield with a number of +1/+1 counters. When it dies, you may put its +1/+1 counters on target artifact creature.",
    "Myriad": "Whenever this creature attacks, for each opponent other than defending player, you may create a token that's a copy of this creature that's tapped and attacking that opponent or a planeswalker they control. Exile the tokens at end of combat.",
    "Outlast": "Pay the outlast cost and tap this creature: Put a +1/+1 counter on it. Outlast only as a sorcery.",
    "Overload": "You may cast this spell for its overload cost. If you do, change its text by replacing all instances of 'target' with 'each.'",
    "Landfall": "Whenever a land enters the battlefield under your control, [effect].",
    "Partner with": "When this creature enters the battlefield, target player may put [partner name] into their hand from their library, then shuffle.",
    "Partner": "You can have two commanders if both have partner.",
    "Metalcraft": "This ability functions as long as you control three or more artifacts.",
    "Islandwalk": "This creature can't be blocked as long as defending player controls an Island.",
    "Treasure": "Artifact token with 'Tap, Sacrifice this artifact: Add one mana of any color.'",
    "Soulbond": "You may pair this creature with another unpaired creature when either enters the battlefield. They remain paired as long as you control both.",
    "Crew": "Tap any number of creatures you control with total power N or more: This Vehicle becomes an artifact creature until end of turn.",
    "Renown": "When this creature deals combat damage to a player, if it isn't renowned, put N +1/+1 counters on it and it becomes renowned.",
    "Escape": "You may cast this card from your graveyard for its escape cost. (Exile N other cards from your graveyard.)",
    "First strike": "This creature deals combat damage before creatures without first strike.",
    "Mill": "Put the top N cards of target player's library into their graveyard.",
    "Encore": "Exile this card from your graveyard: For each opponent, create a token copy that attacks that opponent this turn if able. They gain haste. Sacrifice them at the beginning of the next end step.",
    "Goad": "Until your next turn, that creature attacks each combat if able and attacks a player other than you if able.",
    "Hexproof from": "This permanent can't be the target of [specified quality] spells or abilities your opponents control.",
    "Umbra armor": "If enchanted creature would be destroyed, instead remove all damage from it and destroy this Aura.",
    "Fight": "Each creature deals damage equal to its power to the other.",
    "Reconfigure": "Attach to target creature you control; or unattach from a creature. Reconfigure only as a sorcery.",
    "Afflict": "Whenever this creature becomes blocked, defending player loses N life.",
    "Melee": "Whenever this creature attacks, it gets +1/+1 until end of turn for each opponent you attacked this combat.",
    "Living weapon": "When this Equipment enters the battlefield, create a 0/0 black Germ creature token, then attach this to it.",
    "Exhaust": "This ability is not a standard MTG keyword.",
    "Echo": "At the beginning of your upkeep, if this permanent came under your control since the beginning of your last upkeep, sacrifice it unless you pay its echo cost.",
    "Ward": "Whenever this permanent becomes the target of a spell or ability an opponent controls, counter it unless that player pays N.",
    "Multikicker": "You may pay an additional [cost] any number of times as you cast this spell.",
    "Split second": "As long as this spell is on the stack, players can't cast spells or activate abilities that aren't mana abilities.",
    "Improvise": "Your artifacts can help cast this spell. Each artifact you tap after you're done activating mana abilities pays for {1}.",
    "Monstrosity": "If this creature isn't monstrous, put N +1/+1 counters on it and it becomes monstrous.",
    "Plot": "You may pay [cost] and exile this card from your hand. Cast it as a sorcery on a later turn without paying its mana cost.",
    "Spree": "Choose one or more modes. As an additional cost to cast this spell, pay the costs associated with those modes.",
    "Changeling": "This card is every creature type.",
    "Gift": "You may cast this spell for its gift cost. If you do, [effect].",
    "Collect evidence": "Exile cards from your graveyard with total mana value N or greater.",
    "Surveil": "Look at the top N cards of your library. Put any number into your graveyard and the rest on top in any order.",
    "Investigate": "Create a Clue token. (It's an artifact with '2, Sacrifice this artifact: Draw a card.')",
    "Dethrone": "Whenever this creature attacks the player with the most life or tied for most life, put a +1/+1 counter on it.",
    "Food": "A Food is an artifact with '2, T: Sacrifice this artifact: You gain 3 life.'",
    "Disguise": "You may cast this card face down as a 2/2 creature with ward 2. Turn it face up any time for its disguise cost.",
    "Mentor": "Whenever this creature attacks, put a +1/+1 counter on target attacking creature with lesser power.",
    "Offspring": "When this creature dies, create a token that's a copy of it, except it's 1/1 and has no abilities.",
    "Mobilize": "Tap this creature: Untap another target creature.",
    "Suspect": "A suspected creature has menace and can't block.",
    "Double strike": "This creature deals both first-strike and regular combat damage.",
    "Proliferate": "Choose any number of permanents and/or players with counters. Give each another counter of a kind already there.",
    "Saddle": "Tap any number of creatures you control with total power N or more: This Mount becomes a creature until end of turn.",
    "Valiant": "Whenever this creature attacks alone, it gets +1/+1 until end of turn.",
    "Fabricate": "When this creature enters the battlefield, put N +1/+1 counters on it or create N 1/1 colorless Servo artifact creature tokens.",
    "Forage": "You may exile a card from your graveyard. If you do, [effect].",
    "Flanking": "Whenever a creature without flanking blocks this creature, the blocking creature gets -1/-1 until end of turn.",
    "Threshold": "As long as seven or more cards are in your graveyard, [effect].",
    "Flurry": "Whenever you cast a spell, [effect].",
    "Battle Cry": "Whenever this creature attacks, each other attacking creature gets +1/+0 until end of turn.",
    "Harmonize": "Draw three cards.",
    "Cloak": "Put the card onto the battlefield face down as a 2/2 creature with ward 2. Turn it face up any time for its mana cost if it's a creature card.",
    "Landcycling": "Pay [cost], discard this card: Search your library for a land card, reveal it, put it into your hand, then shuffle.",
    "Basic landcycling": "Pay [cost], discard this card: Search your library for a basic land card, reveal it, put it into your hand, then shuffle.",
    "Typecycling": "Pay [cost], discard this card: Search your library for a card of the specified type, reveal it, put it into your hand, then shuffle.",
    "Manifest": "Put the card onto the battlefield face down as a 2/2 creature. Turn it face up any time for its mana cost if it's a creature card.",
    "Lieutenant": "As long as you control your commander, [effect].",
    "Magecraft": "Whenever you cast or copy an instant or sorcery spell, [effect].",
    "Tempting offer": "When this spell resolves, each opponent may choose to copy it. For each opponent who does, [effect].",
    "Council's dilemma": "When this spell resolves, each player votes for one of two options. Then, [effect based on votes].",
    "Demonstrate": "When you cast this spell, you may copy it. If you do, choose an opponent to also copy it. The copies may choose new targets.",
    "Eternalize": "Pay [cost], exile this card from your graveyard: Create a token that's a copy of it, except it's a 4/4 black Zombie with no mana cost.",
    "Exert": "When this creature attacks, you may choose to exert it. If you do, it won't untap during your next untap step, and [effect].",
    "Riot": "This creature enters the battlefield with your choice of a +1/+1 counter or haste.",
    "Connive": "Draw a card, then discard a card. If you discarded a nonland card, put a +1/+1 counter on this creature.",
    "Channel": "Pay [cost], discard this card: [effect].",
    "Shadow": "This creature can block or be blocked only by creatures with shadow.",
    "Enrage": "A triggered ability that activates when the creature is dealt damage, providing beneficial effects.",
    "Corrupted": "An ability word that grants enhanced effects if an opponent has three or more poison counters.",
    "Role token": "Colorless Aura enchantment tokens that attach to creatures, granting specific abilities; only one Role per creature per player.",
    "Discover": "A keyword action where you exile cards from the top of your library until you exile a nonland card with mana value X or less. You may cast that card without paying its mana cost or put it into your hand.",
    "Eerie": "A triggered ability that activates whenever an enchantment enters the battlefield under your control or when you fully unlock a Room.",
    "Addendum": "An ability word that provides additional effects if the spell is cast during your main phase.",
    "Explore": "A keyword action where you reveal the top card of your library. If it's a land, put it into your hand; otherwise, put a +1/+1 counter on the creature and choose to keep the card on top or put it into your graveyard.",
    "Compleated": "A keyword ability allowing Planeswalkers to be cast using Phyrexian mana; if life is paid, the Planeswalker enters with fewer loyalty counters.",
    "Prototype": "A keyword ability that allows you to cast an artifact creature card for an alternative cost, resulting in a creature with different power, toughness, and mana cost but retaining its abilities.",
    "Assist": "A keyword ability that allows another player to help pay for the generic mana portion of a spell's cost.",
    "Transform": "A keyword action that turns a double-faced card to its other face, changing its characteristics.",
    "Descend": "A mechanic that refers to putting a permanent card into your graveyard from anywhere, triggering various effects.",
    "Alliance": "An ability word that triggers whenever another creature enters the battlefield under your control, providing various effects.",
    "Incubate": "A keyword action that creates an Incubator token with a specified number of +1/+1 counters, which can later be transformed into a creature.",
    "Pack tactics": "An ability word that triggers if you attack with creatures totaling power 6 or greater, granting various bonuses.",
    "Coven": "An ability word that provides effects if you control three or more creatures with different powers.",
    "Blitz": "A keyword ability that allows you to cast a creature for an alternative cost, granting it haste and causing it to be sacrificed at the beginning of the next end step, drawing a card upon death.",
    "Cleave": "A keyword ability that allows you to cast a spell for an alternative cost to ignore words in square brackets in its rules text.",
    "Boast": "An activated ability that can be used once each turn if the creature attacked that turn.",
    "Disturb": "A keyword ability that allows you to cast the backside of a double-faced card from your graveyard for its disturb cost.",
    "Bargain": "An ability word that provides additional effects if you sacrifice an artifact, enchantment, or token as you cast the spell.",
    "Adapt": "A keyword action that allows you to put +1/+1 counters on a creature if it has none.",
    "Toxic": "A keyword ability that causes a creature to deal both combat damage and poison counters equal to its toxic value.",
    "Start your engines!": "An ability word that provides effects when you activate vehicles or other machinery-themed cards.",
    "Venture into the dungeon": "A keyword action that allows you to progress through a dungeon, triggering room abilities.",
    "Training": "A keyword ability that puts a +1/+1 counter on a creature when it attacks alongside another creature with greater power.",
    "Vanishing": "A keyword ability that causes a permanent to enter with a set number of time counters, removing one each upkeep and sacrificing the permanent when none remain.",
    "Foretell": "A keyword ability that allows you to exile a card from your hand face down for 2 mana and cast it later for its foretell cost.",
    "Manifest dread": "An ability word that triggers when you manifest a card, providing additional effects.",
    "Support": "A keyword action that puts +1/+1 counters on each of up to X target creatures.",
    "Adamant": "An ability word that provides additional effects if at least three mana of a single color were spent to cast the spell.",
    "Delirium": "An ability word that provides effects if there are four or more card types among cards in your graveyard.",
    "Celebration": "An ability word that triggers if two or more nonland permanents entered the battlefield under your control this turn.",
    "Ascend": "A keyword ability that grants you the city's blessing if you control ten or more permanents, providing additional effects.",
    "Mutate": "A keyword ability that allows you to cast a creature spell for its mutate cost, merging it with a non-Human creature.",
    "Daybound": "A keyword that indicates a card transforms to its nightbound side if a player casts no spells during their own turn.",
    "Nightbound": "A keyword that indicates a card transforms to its daybound side if a player casts two or more spells during their own turn.",
    "Afterlife": "A keyword ability that creates a specified number of 1/1 white and black Spirit creature tokens with flying when the creature dies.",
    "Read Ahead": "An ability word that allows you to start a saga on any chapter, skipping earlier ones.",
    "Heroic": "An ability word that triggers whenever you cast a spell that targets the creature with heroic, providing various effects.",
    "Domain": "An ability word that provides effects based on the number of basic land types among lands you control.",
    "Spectacle": "A keyword ability that allows you to cast a spell for an alternative cost if an opponent lost life this turn.",
    "Converge": "An ability word that provides effects based on the number of colors of mana spent to cast the spell.",
    "Grandeur": "An ability word that allows you to discard a card with the same name as the creature to activate a special ability.",
    "Meld": "A keyword action that combines two specific cards into one oversized card with combined abilities.",
    "Buyback": "A keyword ability that allows you to pay an additional cost to return the spell to your hand upon resolution.",
    "Enlist": "A keyword ability that allows you to tap a non-attacking creature to add its power to the attacking creature's power.",
    "Casualty": "A keyword ability that allows you to sacrifice a creature with power N or greater to copy the spell.",
    "Fathomless descent": "An ability word that provides effects based on the number of permanent cards in your graveyard.",
    "Raid": "An ability word that provides effects if you attacked with a creature this turn.",
    "Endure": "An ability word that provides effects if you have taken damage this turn.",
    "Constellation": "An ability word that triggers whenever an enchantment enters the battlefield under your control.",
    "Plainscycling": "A keyword ability that allows you to pay a cost to discard the card and search your library for a Plains card.",
    "Amass": "A keyword action that creates a 0/0 Army creature token and puts a specified number of +1/+1 counters on it, or adds counters to an existing Army.",
    "Survival": "An ability word that provides effects if you have fewer cards in hand than an opponent.",
    "Backup": "A keyword ability that allows you to put +1/+1 counters on a creature and grant it abilities from the source card.",
    "Revolt": "An ability word that provides effects if a permanent you controlled left the battlefield this turn.",
    "Replicate": "A keyword ability that allows you to copy a spell for each time you pay its replicate cost.",
    "Max speed": "An ability word that provides effects if you control the creature with the highest power.",
    "Bloodrush": "A keyword ability that allows you to discard the card to give an attacking creature a temporary boost.",
    "Mountaincycling": "A keyword ability that allows you to pay a cost to discard the card and search your library for a Mountain card.",
    "Detain": "A keyword action that prevents a permanent from attacking, blocking, or activating abilities until your next turn.",
    "Fateful hour": "An ability word that provides effects if you have 5 or fewer life.",
    "Learn": "A keyword action that allows you to reveal a Lesson card from outside the game and put it into your hand or discard a card to draw a card.",
    "Craft": "An ability word that allows you to transform an artifact by exiling specified cards.",
    "Hellbent": "An ability word that provides effects if you have no cards in hand.",
    "Reinforce": "A keyword ability that allows you to discard the card to put +1/+1 counters on a creature.",
    "For Mirrodin!": "An ability word that creates a 2/2 red Rebel creature token and attaches the Equipment to it.",
    "Evolve": "A keyword ability that puts a +1/+1 counter on a creature when another creature with greater power or toughness enters the battlefield under your control.",
    "Swampcycling": "A keyword ability that allows you to pay a cost to discard the card and search your library for a Swamp card.",
    "Escalate": "A keyword ability that allows you to pay additional costs to choose more modes on a modal spell.",
    "Companion": "A keyword ability that allows you to designate a card as your companion if your deck meets certain conditions, allowing you to cast it from outside the game.",
    "Devour": "A keyword ability that allows you to sacrifice creatures as the creature enters the battlefield, putting +1/+1 counters on it for each sacrificed creature.",
    "Forestcycling": "A keyword ability that allows you to pay a cost to discard the card and search your library for a Forest card.",
    "Undergrowth": "An ability word that provides effects based on the number of creature cards in your graveyard.",
    "Impending": "An ability word that provides effects if a certain condition is about to be met.",
    "Spell mastery": "An ability word that provides effects if there are two or more instant and/or sorcery cards in your graveyard.",
    "Slivercycling": "A keyword ability that allows you to pay a cost to discard the card and search your library for a Sliver card.",
    "Splice": "A keyword ability that allows you to add the effects of one spell to another by paying its splice cost.",
    "Devoid": "A keyword ability that makes a card colorless, regardless of its mana cost.",
    "Emerge": "An alternative casting cost that allows you to sacrifice a creature and pay the emerge cost minus the sacrificed creature's mana value to cast a spell.",
    "Dash": "An alternative casting cost that gives the creature haste and returns it to its owner's hand at the beginning of the next end step.",
    "Morbid": "An ability word indicating that a spell or ability has an additional or alternative effect if a creature died earlier in the turn.",
    "Eminence": "An ability word that grants a benefit when your commander is in the command zone or on the battlefield.",
    "Swampwalk": "A form of landwalk; a creature with swampwalk is unblockable as long as the defending player controls a Swamp.",
    "Unleash": "You may have this creature enter the battlefield with a +1/+1 counter on it. It can't block as long as it has a +1/+1 counter on it.",
    "Islandcycling": "A variant of cycling that allows you to pay a cost to discard this card and search your library for an Island card.",
    "Level Up": "An activated ability that allows you to put level counters on a creature, unlocking new abilities or stats at certain levels.",
    "Forestwalk": "A form of landwalk; a creature with forestwalk is unblockable as long as the defending player controls a Forest.",
    "Skulk": "This creature can't be blocked by creatures with greater power.",
    "Jump-start": "You may cast this card from your graveyard by discarding a card in addition to paying its other costs. Then exile this card.",
    "Behold": "A keyword action that allows a player to choose a permanent they control of a particular quality or reveal a card of that quality from their hand, usually to pay a cost or get an additional effect.",
    "Sunburst": "This enters the battlefield with a +1/+1 counter on it for each color of mana spent to cast it.",
    "Ferocious": "An ability word that grants a bonus if you control a creature with power 4 or greater.",
    "Battalion": "An ability word that triggers when this creature and at least two other creatures attack, granting a bonus.",
    "Megamorph": "You may cast this card face down as a 2/2 creature for 3 mana. Turn it face up any time for its megamorph cost and put a +1/+1 counter on it.",
    "Strive": "You may pay an additional cost any number of times as you cast this spell to target additional creatures.",
    "Populate": "Create a token that's a copy of a creature token you control.",
    "Imprint": "An ability word indicating that a card exiles another card to grant additional effects.",
    "Decayed": "A creature with decayed can't block. When it attacks, sacrifice it at end of combat.",
    "Bolster": "Choose a creature with the least toughness among creatures you control and put a number of +1/+1 counters on it.",
    "Wizardcycling": "A variant of cycling that allows you to pay a cost to discard this card and search your library for a Wizard card.",
    "Embalm": "Exile this card from your graveyard: Create a token that's a copy of it, except it's a white Zombie with no mana cost. Embalm only as a sorcery.",
    "Undaunted": "This spell costs 1 less to cast for each opponent.",
    "Aftermath": "Cast this spell only from your graveyard. Then exile it.",
    "Formidable": "An ability word that grants a bonus if creatures you control have total power 8 or greater."

    
}