# sets_to_include = ["drc", "tdc", "dsk", "blb", "otj", "mkm", "cmr", "voc", "nec"]
# sets_to_include = ['wc03', 'fmom', 'ons', 'dvd', 'alci', 'phtr', 'cma', 'mznr', 'dft', 'tmom', 'cmb2', 'ptg', 'drk', 'tmh1', 'dtk', 'fjmp', 'tfdn', 'wc02', 'tpr', 'cn2', 'p02', 'dci', 'tc19', 'ph18', 'ptk', 'te01', 'afdn', 'aneo', 'tlci', 'aacr', 'hou', 'dmr', 'tsnc', 'csp', 'm14', 'j25', 'cns', 'dds', 'otj', 'fdmu', 'totj', 'tsr', 'snc', 'fic', 'tmed', 'altc', 'tmkc', 'plst', 'pz2', 'cc2', '10e', 'm13', 'tdag', 'cmr', 'tkhc', 'tjou', 'eve', 'c17', 'tcma', 'ori', 'ddh', 'mbs', 'tsoi', 'w17', 'sok', 'oe01', '9ed', 'tsp', 'togw', 'ywoe', 'm21', 'rex', 'ainr', 'mkm', 'c16', 'tc14', 's99', 'clu', 'dmu', 'dmc', 'nem', 'tpip', 'trna', 'moc', 'tgk2', 'cm2', 'oana', 'hho', 'dsk', 'twar', 'ddl', 'tmma', 'thp1', 'adft', 's00', 'me4', 'tcmr', 'tonc', 'fbro', 'fin', 'tpca', 'tmbs', 'mneo', 'ody', 'tnec', 'scg', 'clb', 'awoe', 'tkhm', 'pls', 'big', 'psdg', 'temn', 'khm', 'ddo', 'dde', 'pip', 'fj22', 'thp2', 'tbro', 'tdtk', 'a25', 'tthb', 'ta25', 'tmh3', 'wc97', 'akhm', 'me3', 'l16', 'm15', 'leg', 'pmic', '7ed', 'akh', 'trix', 'aotj', 'wc01', 'ydsk', 'tdmr', 'ttsr', 'tddi', 'e01', 'mrd', 'twwk', 'tcmm', 'ddt', 'ydmu', 'evg', 'nph', 'tafr', 'lcc', 'ttdm', 'mdmu', 'arn', 'ph20', 'tone', 'inr', 'uds', 'tgk1', 'rix', 'admu', 'yotj', 'ths', 'pf24', 'altr', 'macr', 'eld', 'tdm', 'ulg', 'mh3', 'm11', 'dka', 'tzen', 'neo', 'tm14', 'ph17', 'tblc', 'arc', 'ph22', 'yblb', 'fltr', 'ltc', 'tsb', 'ysnc', 'mm3', 'all', 'cmm', 'mafr', 'fut', 'ybro', 'tdc', 'otc', 'gs1', 'fone', 'j22', 'tvoc', 'hbg', 'j21', 'tdsc', 'chr', 'tugl', 'lci', 'ttdc', 'jmp', 'one', 'tfic', 'tltr', 'tala', 'pssc', 'thb', 'ala', 'tdka', 'gnt', 'tust', 'inv', 'tm11', 'ima', 'mma', 'onc', 'c18', 'mkc', 'kld', 'tdvd', 'sld', 'asnc', 'h17', 'rna', 'troe', '2ed', 'tcn2', 'tund', 'mmh2', 'astx', 'aafr', 'wc98', 'q07', 'tmoc', 'bng', 'unh', 'ncc', 'twoc', 'con', 'dst', 'aznr', 'tdsk', 'gpt', 'tlrw', 'me2', 'ptdmu', 'zen', 'tm19', 'taer', 'brc', 'voc', 'rvr', 'tfin', 'roe', 'pmoa', 'takh', 'tima', 'mone', 'mvow', 'tneo', 'unf', 'ddg', 'lrw', 'tmkm', 'tblb', 'tafc', 'woe', 'wwk', 'ytdm', 'pca', 'tgtc', 'ogw', 'tori', 't10e', 'ddj', 'amh3', 'exo', 'totp', 'mat', 'tbig', 'ffdn', 'tstx', 'afr', 'trex', 'arb', '40k', 't40k', 'ddu', 'tdom', 'gtc', 'aer', 'znr', 'avr', 'tths', 'wth', 'ablb', 'hml', 'ktk', 'nec', '2x2', 'tdmc', 'khc', 'tfth', 'ddf', 'ydft', 'm20', '4ed', 'mid', 'c20', 'c14', 'm3c', '2xm', 'xln', 'ph19', 'rav', 'chk', 'c13', 'mh2', 'ugl', 'tm20', 'fj25', 'tbot', 'frf', 'afc', 'bfz', 'wc00', 'vma', 'mm2', 'tm3c', 'cc1', 'hop', 'tiko', 'tdde', 'twoe', 'amh1', 'aone', 'pcel', 'amid', 'emn', 'ymkm', 'mh1', 'sth', 'tclb', 'dom', 'blc', 'tm15', 'msnc', 'tc20', 'woc', 'amh2', 'iko', 'avow', 'tshm', 'mom', 'ddm', 'tznr', 'amom', '5ed', 'tarb', 'vis', 'me1', 'm12', 'slx', 'mstx', 'blb', 'acmm', 'tktk', 'smh3', 'ylci', 'tgrn', 'pf25', 'mor', 'atq', 'tmid', 'amkm', 'war', 'tbfz', 'ice', 'adsk', 'yone', 'm19', 'c19', 'gvl', 'tunf', 'uma', 'tinr', 'thou', 'fdn', 'ltr', 'tisd', 'prm', 'tbbd', 'ema', 'soi', '5dn', 'tmp', 'opca', 'thp3', 'jvc', 'apc', 'ddi', 't2xm', 'tmh2', 'mclb', 'dgm', 'tcm2', 'vow', 'znc', 'pvan', 'sunf', 'acr', 'tc15', 'teld', 'atdm', 'ddk', 'lgn', 'anb', 'tcns', 'yneo', 'pemn', 'fem', 'gn2', 'tm21', 'ddq', 'f17', 't2x2', 'ust', 'dsc', 'l17', 'ddn', 'txln', 'som', 'bro', 'wc99', 'tdmu', 'fclu', 'm10', 'td2', 'tddt', 'und', 'pcy', 'tkld', 'dis', 'tvow', 'bot', 'mir', 'tuma', 'w16', 'p03', 'rtr', 'tc18', 'mb2', 'bbd', 'mic', 'phel', '8ed', 'tc17', 'ptbro', 'tbth', 'tdft', '6ed', 'tbrc', 'trvr', 'tdrc', 'mbro', 'trtr', 'tema', 'oarc', 'bok', 'tc21', 'gn3', 'usg', 'shm', 'twho', 'ppc1', 'stx', 'c21', 'c15', 'past', 'abro', 'isd', 'mmq', 'plc', 'spe', 'ddr', 'aclb', 'ph21', 'tor', 'f18', 'f12', 'tsom', 'jud', 'totc', 'h2r', 'sum', 'wc04', 'tltc', 'drc', 'ymid', 'mkhm', 'mmid', 'jou', 'cmd', 'who', 'tbng', 'grn', 'ddp', 'tmm3', 'tacr', 'por', 'unk']
sets_to_include = [
    # 2018
    "rix",
    "a25",
    "dom",
    "bbd",
    "m19",
    "grn",
    "uma",
    # 2019
    "rna",
    "war",
    "mh1",
    "m20",
    "eld",
    # 2020
    "thb",
    "iko",
    "m21",
    "2xm",
    "znr",
    "cmr",
    # 2021
    "khm",
    "tsr",
    "stx",
    "mh2",
    "afr",
    "mid",
    "vow",
    # 2022
    "neo",
    "snc",
    "2x2",
    "dmu",
    "bro",
    "j22",
    # 2023
    "one",
    "mom",
    "mat",
    "ltr",
    "woe",
    "lci",
    # 2024
    "rvr",
    "mkm",
    "otj",
    "mh3",
    "blb",
    "dsk",
    "fdn",
    # 2025 (released through May 15)
    "inr",
    "dft",
    "tdm",
]

all_sets = [
    "tstx",
    "tinr",
    "mh3",
    "prm",
    "ulg",
    "tddi",
    "dis",
    "7ed",
    "mm2",
    "eve",
    "ttdc",
    "dst",
    "s99",
    "pf24",
    "scg",
    "tfic",
    "te01",
    "exo",
    "ysnc",
    "wc02",
    "ima",
    "tblc",
    "mznr",
    "tc20",
    "tneo",
    "tdmu",
    "tfth",
    "m3c",
    "ybro",
    "iko",
    "pca",
    "ths",
    "tmoc",
    "dsc",
    "oana",
    "wc04",
    "cc2",
    "onc",
    "ydsk",
    "tnec",
    "opca",
    "bng",
    "mom",
    "tlci",
    "ttsr",
    "ltc",
    "w17",
    "fj25",
    "tdmc",
    "troe",
    "jud",
    "woc",
    "ainr",
    "ncc",
    "tcm2",
    "tbot",
    "leg",
    "ktk",
    "nem",
    "9ed",
    "mneo",
    "dmc",
    "tor",
    "pmic",
    "trna",
    "apc",
    "pmoa",
    "wc99",
    "twar",
    "ust",
    "amh3",
    "ywoe",
    "oarc",
    "cma",
    "tala",
    "tdmr",
    "unk",
    "akh",
    "aer",
    "tddt",
    "totj",
    "aotj",
    "otc",
    "aafr",
    "tmid",
    "thp3",
    "rex",
    "grn",
    "phel",
    "amkm",
    "arc",
    "tuma",
    "afc",
    "2xm",
    "atdm",
    "jou",
    "tsb",
    "afr",
    "ptg",
    "por",
    "pip",
    "tdvd",
    "tvow",
    "clu",
    "td2",
    "cmm",
    "mir",
    "stx",
    "thou",
    "fclu",
    "lgn",
    "fdmu",
    "ice",
    "anb",
    "ydmu",
    "drc",
    "dgm",
    "2ed",
    "und",
    "zen",
    "ddq",
    "tcns",
    "tbfz",
    "tund",
    "neo",
    "avr",
    "dft",
    "ddh",
    "tltr",
    "tznr",
    "tc19",
    "5dn",
    "admu",
    "6ed",
    "tdc",
    "ddk",
    "mkm",
    "brc",
    "nph",
    "f12",
    "mor",
    "dka",
    "evg",
    "tzen",
    "twho",
    "fbro",
    "wc03",
    "tmh2",
    "ddn",
    "soi",
    "moc",
    "thb",
    "tbrc",
    "bro",
    "me3",
    "bfz",
    "m14",
    "t2x2",
    "tmom",
    "l17",
    "khm",
    "f18",
    "temn",
    "drk",
    "tbng",
    "phtr",
    "hml",
    "tm3c",
    "tdka",
    "one",
    "ddf",
    "m11",
    "ody",
    "bot",
    "gpt",
    "altr",
    "tdag",
    "tsnc",
    "tkhm",
    "blc",
    "ablb",
    "mvow",
    "dom",
    "fj22",
    "tc15",
    "avow",
    "bok",
    "t10e",
    "cns",
    "ph19",
    "tpr",
    "dmu",
    "mh1",
    "xln",
    "m15",
    "tbbd",
    "8ed",
    "hop",
    "ddo",
    "aclb",
    "40k",
    "tcmm",
    "tmkm",
    "rix",
    "mma",
    "gn3",
    "hou",
    "tmh1",
    "eld",
    "ddt",
    "slx",
    "fut",
    "hbg",
    "mbs",
    "ddp",
    "mrd",
    "tm20",
    "tgrn",
    "tdsk",
    "znr",
    "twoe",
    "ymkm",
    "togw",
    "ddl",
    "wwk",
    "thp1",
    "voc",
    "ddr",
    "tarb",
    "mafr",
    "tdtk",
    "tltc",
    "cmr",
    "tclb",
    "tmh3",
    "amid",
    "m12",
    "alci",
    "ddu",
    "aacr",
    "clb",
    "tust",
    "emn",
    "tkhc",
    "ons",
    "tblb",
    "rtr",
    "hho",
    "tsoi",
    "tiko",
    "wc01",
    "pz2",
    "tths",
    "dci",
    "dtk",
    "chk",
    "tbig",
    "arn",
    "rvr",
    "tbth",
    "dvd",
    "pemn",
    "yotj",
    "uma",
    "tonc",
    "fltr",
    "adft",
    "atq",
    "p02",
    "cc1",
    "tsr",
    "a25",
    "c18",
    "tone",
    "c13",
    "tdft",
    "rna",
    "ydft",
    "roe",
    "cm2",
    "dds",
    "twoc",
    "frf",
    "tkld",
    "dmr",
    "tori",
    "rav",
    "taer",
    "akhm",
    "kld",
    "c17",
    "ala",
    "tc14",
    "vma",
    "ptbro",
    "khc",
    "w16",
    "f17",
    "h2r",
    "som",
    "amh2",
    "ddj",
    "wth",
    "tm21",
    "ema",
    "ph17",
    "ptk",
    "tacr",
    "ytdm",
    "me2",
    "csp",
    "abro",
    "fin",
    "mm3",
    "twwk",
    "2x2",
    "snc",
    "e01",
    "mmq",
    "sunf",
    "pcy",
    "j21",
    "tc17",
    "tthb",
    "ddm",
    "tmkc",
    "totp",
    "m19",
    "pvan",
    "tunf",
    "lcc",
    "tpip",
    "ori",
    "5ed",
    "plst",
    "tafr",
    "tm15",
    "gtc",
    "blb",
    "ph21",
    "arb",
    "con",
    "unf",
    "cmd",
    "p03",
    "ttdm",
    "spe",
    "tgk2",
    "who",
    "q07",
    "yneo",
    "mat",
    "c15",
    "ddi",
    "me4",
    "psdg",
    "t40k",
    "lci",
    "tsom",
    "ppc1",
    "fone",
    "sth",
    "tpca",
    "macr",
    "j25",
    "tc21",
    "tshm",
    "aneo",
    "asnc",
    "totc",
    "vis",
    "c14",
    "10e",
    "teld",
    "ffdn",
    "tm14",
    "tm19",
    "tdrc",
    "all",
    "mid",
    "4ed",
    "ptdmu",
    "znc",
    "tdde",
    "m13",
    "j22",
    "tgk1",
    "pls",
    "woe",
    "tdsc",
    "trtr",
    "mone",
    "tdom",
    "ymid",
    "shm",
    "cn2",
    "tgtc",
    "nec",
    "aone",
    "mkhm",
    "pf25",
    "inv",
    "oe01",
    "ugl",
    "fem",
    "chr",
    "m21",
    "tktk",
    "tvoc",
    "c21",
    "tcn2",
    "tcma",
    "me1",
    "fmom",
    "l16",
    "isd",
    "mbro",
    "c20",
    "war",
    "aznr",
    "afdn",
    "tafc",
    "usg",
    "c19",
    "tmp",
    "adsk",
    "tsp",
    "altc",
    "fic",
    "lrw",
    "tfin",
    "acmm",
    "dde",
    "mb2",
    "mdmu",
    "amom",
    "wc98",
    "ylci",
    "txln",
    "mmid",
    "uds",
    "sok",
    "ta25",
    "mstx",
    "gn2",
    "mmh2",
    "tisd",
    "dsk",
    "mclb",
    "ltr",
    "pcel",
    "tlrw",
    "m20",
    "trix",
    "h17",
    "msnc",
    "sld",
    "wc00",
    "jmp",
    "unh",
    "tima",
    "gs1",
    "mic",
    "jvc",
    "bbd",
    "ph22",
    "amh1",
    "m10",
    "ddg",
    "tmbs",
    "smh3",
    "tfdn",
    "acr",
    "tdm",
    "mh2",
    "tmed",
    "fdn",
    "big",
    "yblb",
    "wc97",
    "tc18",
    "tcmr",
    "ph18",
    "ph20",
    "otj",
    "t2xm",
    "tm11",
    "tjou",
    "cmb2",
    "mkc",
    "ogw",
    "astx",
    "gvl",
    "thp2",
    "gnt",
    "tugl",
    "trvr",
    "past",
    "trex",
    "fjmp",
    "s00",
    "yone",
    "plc",
    "sum",
    "takh",
    "vow",
    "inr",
    "tbro",
    "awoe",
    "tmm3",
    "c16",
    "tema",
    "tmma",
    "pssc",
]

tags_included = {
    "tutor-to-hand",
    "gives pp counters",
    "reanimate-cast",
    "creature type erratum",
    "gives indestructible",
    "anthem",
    "removal-creature-burn",
    "utility mana rock",
    "graveyard fuel-self",
    "boost-toughness",
    "out of color token",
    "sacrifice self",
    "tutor-land-basic",
    "synergy-planeswalker",
    "mana value matters",
    "card advantage (no-draw)",
    "untaps self",
    "activate from hand",
    "reflexive trigger",
    "synergy-attacker",
    "tribal-human",
    "power matters-self",
    "ferocious",
    "gains indestructible",
    "sacrifice outlet-enchantment",
    "unique token",
    "tribal-army",
    "sweeper-creature-toughness",
    "removal-enchantment-destroy",
    "virtual legendary",
    "gives menace",
    "gains pp counters",
    "loot",
    "thoughtseize",
    "untapper-creature",
    "namesake-spell",
    "single target instant/sorcery",
    "death trigger-self",
    "adds multiple mana",
    "reanimate-self",
    "rhyming name",
    "gives trample",
    "synergy-token",
    "cards in graveyard matter",
    "tribal-dragon",
    "discard with set mechanic",
    "morbid",
    "hate-blocker",
    "requires notation",
    "manaless value",
    "tribal-warrior",
    "power boost to all",
    "synergy-enchantment",
    "synergy-white",
    "removal-planeswalker-destroy",
    "card types in graveyard matter",
    "hate-graveyard",
    "virtual vanilla",
    "cost-reducer-self",
    "trigger from graveyard",
    "oversized",
    "impulse-land",
    "mill-any",
    "synergy-legendary",
    "gives deathtouch",
    "pp counters matter",
    "tutor-land-to-battlefield",
    "french vanilla",
    "discard matters",
    "intervening if clause",
    "regrowth-self",
    "donate token",
    "drain life",
    "opponent loses life",
    "tutor-to-battlefield",
    "tribal-vampire",
    "burn with set mechanic",
    "punny name",
    "offcolor ability",
    "top deck manipulation",
    "saboteur",
    "gains menace",
    "creaturefall",
    "titan trigger",
    "toughness matters",
    "sacrifice outlet-artifact",
    "symmetrical",
    "egg",
    "tutored by name",
    "etb-self",
    "gives flying",
    "ramp",
    "gives hexproof",
    "utility land",
    "offcolor additional cost",
    "gives skulk",
    "death trigger",
    "tap fuel-creature",
    "humble",
    "gains haste",
    "selective group hug",
    "gains lifelink",
    "synergy-attacker-self",
    "removal-planeswalker-burn",
    "tribal-rogue",
    "temporary token",
    "cantrip",
    "draw matters",
    "surveil",
    "non mana ability mana",
    "alliteration",
    "synergy-sorcery",
    "removal-creature-exile",
    "firebreathing",
    "portmanteau",
    "pair-commander",
    "temporary reanimation",
    "synergy-sacrifice",
    "burn any",
    "mix-and-match",
    "rummage",
    "impulse",
    "counterspell-soft",
    "removal-creature-bounce",
    "theft-cast",
    "animate land",
    "removal-artifact-destroy",
    "pinger",
    "bounce-self",
    "sweeper-creature-burn",
    "gives mana ability",
    "synergy-green",
    "gains flying",
    "unblockable",
    "activate from graveyard",
    "regrowth-creature",
    "delayed triggered ability",
    "power matters",
    "impulsive draw",
    "free-cast-another",
    "disenchant/naturalize",
    "mulch",
    "restricted mana",
    "sacrifice outlet-land",
    "reanimate-creature",
    "cost reducer",
    "undergrowth",
    "type change",
    "mana dork",
    "unique mana cost",
    "conjure",
    "tribal coupling",
    "gives vigilance",
    "virtual french vanilla",
    "cast-from-graveyard",
    "heroic",
    "removal-creature",
    "modal",
    "alternate-cost-tap-creature",
    "discard",
    "protects-creature",
    "tapper-creature",
    "synergy-artifact",
    "evasion",
    "dnd monster",
    "giant growth",
    "gives double strike",
    "counters matter",
    "animate self",
    "tapland",
    "discard outlet",
    "noncreature tribal",
    "synergy-noncreature",
    "tribal-wizard",
    "tutor-card",
    "life payment",
    "rescue-creature",
    "token generator",
    "lifegain",
    "bear with set's mechanic",
    "draw",
    "cast trigger-you",
    "rhystic",
    "burn player",
    "flicker-creature",
    "fun ruling",
    "tome",
    "landfall",
    "prevent blocker",
    "gives first strike",
    "repeatable draw",
    "removal-creature-fight",
    "drawback",
    "block trigger",
    "tutor-creature",
    "interchangeable name",
    "poisonous",
    "hatebear",
    "unique type line",
    "hate-counterspell",
    "one-sided fight",
    "creature count matters",
    "synergy-red",
    "copy-creature",
    "attack trigger",
    "hate-artifact",
    "graveyard fuel",
    "repeatable removal",
    "counterspell with set mechanic",
    "martyr",
    "graveyard fuel-creature",
    "consult-cast",
    "synergy-blue",
    "impulse-onto-battlefield",
    "unique counter",
    "tribal-cleric",
    "shapechange",
    "lands matter",
    "repeatable crime",
    "giant growth with set mechanic",
    "fetchable",
    "conditional tapland",
    "curiosity",
    "hate-set-mechanic",
    "nonbasic-basic-land-type",
    "sacrifice outlet-creature",
    "copy-sorcery",
    "single english word name",
    "life loss matters",
    "lifegain matters",
    "hate-flying",
    "gives haste",
    "hate-attacker",
    "mill-self",
    "gives lifelink",
    "refund",
    "theft-creature",
    "freeze-creature",
    "swap removal",
    "synergy-vehicle",
    "sweeper-creature-destroy",
    "free sacrifice outlet",
    "copy-instant",
    "removal-nonland-bounce",
    "hate-tapped",
    "synergy-flying",
    "synergy-equipment",
    "repeatable token generator",
    "exponential",
    "removal-creature-toughness",
    "gives reach",
    "impulse-creature",
    "removal-creature-destroy",
    "damage prevention",
    "prevent attack",
    "synergy-black",
    "boost-power",
    "synergy-aura",
    "day/night",
    "synergy-color-share",
    "synergy-token-creature",
    "synergy-instant",
    "sweeper-one-sided",
    "shade pump",
    "mana sink",
    "combat trick",
    "hate-high-pt",
    "removal-creature-sacrifice",
    "grants flashback",
    "mana filter",
    "passive ability",
}

bulk_file = "datasets/bulk/oracle-cards-20250726090430.json"  # Your input file
# bulk_file = "datasets/bulk/oracle-cards-20250514090324.json"


scrapped_store = "datasets/scryfallTagger_data/store_scrapped.json"
output_scrapped_dir = "datasets/scryfallTagger_data/"
X_CSRF_Token = "NJrEkdbRZu_iwSZZ7FAbwKUMt_7qzPxJtIa_tHGEN-7vVlq0I-o9ckJ366KrhkDQikklgLtN2whyJ9sqCoC9Pw"
cookie = (
    "cf_clearance=_2EOdsOYK.0lTg0KeaSniHX5vocdcKbdqlBoN3WwP6E-1747211339-1.2.1.1-"
    "J82IFA63.45lHJApa0xCTDHGmFnNJl5M2a26oG8_OKRqBtj7LFgmJ5SL2n4dKaue8cRDL7xkx_tTkPTDzZD5Cdsa8zIIAL7LmiqlH8QcxpNZwabcwVab4OPRGgY.hhKDcpmNwdjbVnFIpaSyQpjgN9cLpm2BWLFGaP2vRqDkDITdKyKGXvzM_PXNbt7RrWJizwWDV4nVG85Uxj1zbZTd_wu7rLrprwUFRz8Ta7IdlJTjGjifjtVfyW.foEMCo5DIts68RHrgXIw1e_Xa7IfoIdNsY1MR2Rm8hnX5YCLlzSoTHYUVL1JdU3kTOlwxQ55H5VQ2oXnmt3vKax0VtljqmrLVg.cQOQk57bbwr_TNzEezuuNxKedlcSpnr3csjY..; "
    "auth_token=vBCCIR5nqj8COFOppwSEajmJhJuoD5MV1hjlVacUuLzGvJoLEu6GkA8vZ4zRPxklwG1RiAmYQ7A1rCyeqAO4W2iCRwdEE7WDdApx%2BbBDLqwNPquT1IiuSSS3qq5tg%2FnmsnZ95QpySuy%2F35jQTGEuTsRliZKXn7FuAJc0xgaoqHR6dh9QY9CiHg%3D%3D--n%2FriRWa1kSoxWfHF--1N3fcygpfup0QgUxydH7Kw%3D%3D; "
    "_scryfall_tagger_session=Vh6BfgNIWDX3ZlKhSHlsHTyxNL98JmHgXVZBHQNRgewBDX7l4i7QUgMojaH+fepdTCw6IhL70gyB+bUXmudFoyJBjd+Dqnx5t4mF5rBvC3lyEVXmI/3WzOw+IkWKeqwPuoqI7XqxfXywFyyMgaHO4DlCzb0iDm57+eH9AQgu1UWN05wMU9PDDuU9e6agM67vyUt2LBcd4iOj0C/JkhNUEy+zIa+nBDPUfCp7wz0pydjKWSU3Q6p7icNXzSXWq84EXOLKRTKuuTJ857pzRqwjeG3h1ecI6Y8APiU9oJWXSqs=--Le0MPBwqIoT5BLJB--SJwJ1LySA0F4qjK4XnuuWQ=="
)


processed_json = "datasets/processed/indent/commander_legal_cards20250625183217.json"

processed_tag_dir = "datasets/processed/tag_included/"

embedding_file = "datasets/processed/embedding/card_embs_20250515151222.json"

split_dir = "datasets/split/"

mtg_sets_dict = {
    "10e": "Tenth Edition",
    "2ed": "Unlimited Edition",
    "2x2": "Double Masters 2022",
    "2xm": "Double Masters",
    "30a": "30th Anniversary Edition",
    "3ed": "Revised Edition",
    "40k": "Warhammer 40,000 Commander",
    "4bb": "Fourth Edition Foreign Black Border",
    "4ed": "Fourth Edition",
    "5dn": "Fifth Dawn",
    "5ed": "Fifth Edition",
    "6ed": "Classic Sixth Edition",
    "7ed": "Seventh Edition",
    "8ed": "Eighth Edition",
    "9ed": "Ninth Edition",
    "a25": "Masters 25",
    "aacr": "Assassin's Creed Art Series",
    "aafr": "Adventures in the Forgotten Realms Art Series",
    "ablb": "Bloomburrow Art Series",
    "abro": "The Brothers' War Art Series",
    "aclb": "Battle for Baldur's Gate Art Series",
    "acmm": "Commander Masters Art Series",
    "acr": "Assassin's Creed",
    "adft": "Aetherdrift Art Series",
    "admu": "Dominaria United Art Series",
    "adsk": "Duskmourn: House of Horror Art Series",
    "aer": "Aether Revolt",
    "afc": "Forgotten Realms Commander",
    "afdn": "Foundations Art Series",
    "afin": "Final Fantasy Art Series",
    "afr": "Adventures in the Forgotten Realms",
    "ainr": "Innistrad Remastered Art Series",
    "ajmp": "Jumpstart Arena Exclusives",
    "akh": "Amonkhet",
    "akhm": "Kaldheim Art Series",
    "akr": "Amonkhet Remastered",
    "ala": "Shards of Alara",
    "alci": "The Lost Caverns of Ixalan Art Series",
    "all": "Alliances",
    "altc": "Tales of Middle-earth Scene Box",
    "altr": "Tales of Middle-earth Art Series",
    "amh1": "Modern Horizons Art Series",
    "amh2": "Modern Horizons 2 Art Series",
    "amh3": "Modern Horizons 3 Art Series",
    "amid": "Midnight Hunt Art Series",
    "amkm": "Murders at Karlov Manor Art Series",
    "amom": "March of the Machine Art Series",
    "ana": "Arena New Player Experience",
    "anb": "Arena Beginner Set",
    "aneo": "Neon Dynasty Art Series",
    "aone": "Phyrexia: All Will Be One Art Series",
    "aotj": "Outlaws of Thunder Junction Art Series",
    "apc": "Apocalypse",
    "arb": "Alara Reborn",
    "arc": "Archenemy",
    "arn": "Arabian Nights",
    "asnc": "New Capenna Art Series",
    "astx": "Strixhaven Art Series",
    "atdm": "Tarkir: Dragonstorm Art Series",
    "ath": "Anthologies",
    "atq": "Antiquities",
    "avow": "Crimson Vow Art Series",
    "avr": "Avacyn Restored",
    "awoe": "Wilds of Eldraine Art Series",
    "aznr": "Zendikar Rising Art Series",
    "bbd": "Battlebond",
    "bchr": "Chronicles Foreign Black Border",
    "bfz": "Battle for Zendikar",
    "big": "The Big Score",
    "blb": "Bloomburrow",
    "blc": "Bloomburrow Commander",
    "bng": "Born of the Gods",
    "bok": "Betrayers of Kamigawa",
    "bot": "Transformers",
    "brb": "Battle Royale Box Set",
    "brc": "The Brothers' War Commander",
    "bro": "The Brothers' War",
    "brr": "The Brothers' War Retro Artifacts",
    "btd": "Beatdown Box Set",
    "c13": "Commander 2013",
    "c14": "Commander 2014",
    "c15": "Commander 2015",
    "c16": "Commander 2016",
    "c17": "Commander 2017",
    "c18": "Commander 2018",
    "c19": "Commander 2019",
    "c20": "Commander 2020",
    "c21": "Commander 2021",
    "cc1": "Commander Collection: Green",
    "cc2": "Commander Collection: Black",
    "ced": "Collectors' Edition",
    "cei": "Intl. Collectors' Edition",
    "chk": "Champions of Kamigawa",
    "chr": "Chronicles",
    "clb": "Commander Legends: Battle for Baldur's Gate",
    "clu": "Ravnica: Clue Edition",
    "cm1": "Commander's Arsenal",
    "cm2": "Commander Anthology Volume II",
    "cma": "Commander Anthology",
    "cmb1": "Mystery Booster Playtest Cards 2019",
    "cmb2": "Mystery Booster Playtest Cards 2021",
    "cmd": "Commander 2011",
    "cmm": "Commander Masters",
    "cmr": "Commander Legends",
    "cn2": "Conspiracy: Take the Crown",
    "cns": "Conspiracy",
    "con": "Conflux",
    "cp1": "Magic 2015 Clash Pack",
    "cp2": "Fate Reforged Clash Pack",
    "cp3": "Magic Origins Clash Pack",
    "csp": "Coldsnap",
    "cst": "Coldsnap Theme Decks",
    "dbl": "Innistrad: Double Feature",
    "dci": "DCI Promos",
    "dd1": "Duel Decks: Elves vs. Goblins",
    "dd2": "Duel Decks: Jace vs. Chandra",
    "ddc": "Duel Decks: Divine vs. Demonic",
    "ddd": "Duel Decks: Garruk vs. Liliana",
    "dde": "Duel Decks: Phyrexia vs. the Coalition",
    "ddf": "Duel Decks: Elspeth vs. Tezzeret",
    "ddg": "Duel Decks: Knights vs. Dragons",
    "ddh": "Duel Decks: Ajani vs. Nicol Bolas",
    "ddi": "Duel Decks: Venser vs. Koth",
    "ddj": "Duel Decks: Izzet vs. Golgari",
    "ddk": "Duel Decks: Sorin vs. Tibalt",
    "ddl": "Duel Decks: Heroes vs. Monsters",
    "ddm": "Duel Decks: Jace vs. Vraska",
    "ddn": "Duel Decks: Speed vs. Cunning",
    "ddo": "Duel Decks: Elspeth vs. Kiora",
    "ddp": "Duel Decks: Zendikar vs. Eldrazi",
    "ddq": "Duel Decks: Blessed vs. Cursed",
    "ddr": "Duel Decks: Nissa vs. Ob Nixilis",
    "dds": "Duel Decks: Mind vs. Might",
    "ddt": "Duel Decks: Merfolk vs. Goblins",
    "ddu": "Duel Decks: Elves vs. Inventors",
    "dft": "Aetherdrift",
    "dgm": "Dragon's Maze",
    "dis": "Dissension",
    "dka": "Dark Ascension",
    "dkm": "Deckmasters",
    "dmc": "Dominaria United Commander",
    "dmr": "Dominaria Remastered",
    "dmu": "Dominaria United",
    "dom": "Dominaria",
    "dpa": "Duels of the Planeswalkers",
    "drb": "From the Vault: Dragons",
    "drc": "Aetherdrift Commander",
    "drk": "The Dark",
    "dsc": "Duskmourn: House of Horror Commander",
    "dsk": "Duskmourn: House of Horror",
    "dst": "Darksteel",
    "dtk": "Dragons of Tarkir",
    "dvd": "Duel Decks Anthology: Divine vs. Demonic",
    "e01": "Archenemy: Nicol Bolas",
    "e02": "Explorers of Ixalan",
    "ea1": "Explorer Anthology 1",
    "ea2": "Explorer Anthology 2",
    "ea3": "Explorer Anthology 3",
    "eld": "Throne of Eldraine",
    "ema": "Eternal Masters",
    "emn": "Eldritch Moon",
    "eoc": "Edge of Eternities Commander",
    "eoe": "Edge of Eternities",
    "eos": "Edge of Eternities: Stellar Sights",
    "eve": "Eventide",
    "evg": "Duel Decks Anthology: Elves vs. Goblins",
    "exo": "Exodus",
    "exp": "Zendikar Expeditions",
    "f01": "Friday Night Magic 2001",
    "f02": "Friday Night Magic 2002",
    "f03": "Friday Night Magic 2003",
    "f04": "Friday Night Magic 2004",
    "f05": "Friday Night Magic 2005",
    "f06": "Friday Night Magic 2006",
    "f07": "Friday Night Magic 2007",
    "f08": "Friday Night Magic 2008",
    "f09": "Friday Night Magic 2009",
    "f10": "Friday Night Magic 2010",
    "f11": "Friday Night Magic 2011",
    "f12": "Friday Night Magic 2012",
    "f13": "Friday Night Magic 2013",
    "f14": "Friday Night Magic 2014",
    "f15": "Friday Night Magic 2015",
    "f16": "Friday Night Magic 2016",
    "f17": "Friday Night Magic 2017",
    "f18": "Friday Night Magic 2018",
    "fbb": "Foreign Black Border",
    "fbro": "The Brothers' War Jumpstart Front Cards",
    "fca": "Final Fantasy: Through the Ages",
    "fclu": "Ravnica: Clue Edition Front Cards",
    "fdc": "Foundations Commander",
    "fdmu": "Dominaria United Jumpstart Front Cards",
    "fdn": "Foundations",
    "fem": "Fallen Empires",
    "ffdn": "Foundations Front Cards",
    "fic": "Final Fantasy Commander",
    "fin": "Final Fantasy",
    "fj22": "Jumpstart 2022 Front Cards",
    "fj25": "Foundations Jumpstart Front Cards",
    "fjmp": "Jumpstart Front Cards",
    "fltr": "Tales of Middle-earth Front Cards",
    "fmom": "March of the Machine Jumpstart Front Cards",
    "fnm": "Friday Night Magic 2000",
    "fone": "Phyrexia: All Will Be One Jumpstart Front Cards",
    "frf": "Fate Reforged",
    "fut": "Future Sight",
    "g00": "Judge Gift Cards 2000",
    "g01": "Judge Gift Cards 2001",
    "g02": "Judge Gift Cards 2002",
    "g03": "Judge Gift Cards 2003",
    "g04": "Judge Gift Cards 2004",
    "g05": "Judge Gift Cards 2005",
    "g06": "Judge Gift Cards 2006",
    "g07": "Judge Gift Cards 2007",
    "g08": "Judge Gift Cards 2008",
    "g09": "Judge Gift Cards 2009",
    "g10": "Judge Gift Cards 2010",
    "g11": "Judge Gift Cards 2011",
    "g17": "2017 Gift Pack",
    "g18": "M19 Gift Pack",
    "g99": "Judge Gift Cards 1999",
    "gdy": "Game Day Promos",
    "gk1": "GRN Guild Kit",
    "gk2": "RNA Guild Kit",
    "gn2": "Game Night 2019",
    "gn3": "Game Night: Free-for-All",
    "gnt": "Game Night",
    "gpt": "Guildpact",
    "grn": "Guilds of Ravnica",
    "gs1": "Global Series Jiang Yanggu & Mu Yanling",
    "gtc": "Gatecrash",
    "gvl": "Duel Decks Anthology: Garruk vs. Liliana",
    "h09": "Premium Deck Series: Slivers",
    "h17": "HasCon 2017",
    "h1r": "Modern Horizons 1 Timeshifts",
    "h2r": "Modern Horizons 2 Timeshifts",
    "ha1": "Historic Anthology 1",
    "ha2": "Historic Anthology 2",
    "ha3": "Historic Anthology 3",
    "ha4": "Historic Anthology 4",
    "ha5": "Historic Anthology 5",
    "ha6": "Historic Anthology 6",
    "ha7": "Historic Anthology 7",
    "hbg": "Alchemy Horizons: Baldur's Gate",
    "hho": "Happy Holidays",
    "hml": "Homelands",
    "hop": "Planechase",
    "hou": "Hour of Devastation",
    "ice": "Ice Age",
    "iko": "Ikoria: Lair of Behemoths",
    "ima": "Iconic Masters",
    "inr": "Innistrad Remastered",
    "inv": "Invasion",
    "isd": "Innistrad",
    "itp": "Introductory Two-Player Set",
    "j12": "Judge Gift Cards 2012",
    "j13": "Judge Gift Cards 2013",
    "j14": "Judge Gift Cards 2014",
    "j15": "Judge Gift Cards 2015",
    "j16": "Judge Gift Cards 2016",
    "j17": "Judge Gift Cards 2017",
    "j18": "Judge Gift Cards 2018",
    "j19": "Judge Gift Cards 2019",
    "j20": "Judge Gift Cards 2020",
    "j21": "Jumpstart: Historic Horizons",
    "j22": "Jumpstart 2022",
    "j25": "Foundations Jumpstart",
    "jgp": "Judge Gift Cards 1998",
    "jmp": "Jumpstart",
    "jou": "Journey into Nyx",
    "jp1": "Hobby Japan Promos",
    "jud": "Judgment",
    "jvc": "Duel Decks Anthology: Jace vs. Chandra",
    "khc": "Kaldheim Commander",
    "khm": "Kaldheim",
    "kld": "Kaladesh",
    "klr": "Kaladesh Remastered",
    "ktk": "Khans of Tarkir",
    "l12": "League Tokens 2012",
    "l13": "League Tokens 2013",
    "l14": "League Tokens 2014",
    "l15": "League Tokens 2015",
    "l16": "League Tokens 2016",
    "l17": "League Tokens 2017",
    "lcc": "The Lost Caverns of Ixalan Commander",
    "lci": "The Lost Caverns of Ixalan",
    "lea": "Limited Edition Alpha",
    "leb": "Limited Edition Beta",
    "leg": "Legends",
    "lgn": "Legions",
    "lrw": "Lorwyn",
    "ltc": "Tales of Middle-earth Commander",
    "ltr": "The Lord of the Rings: Tales of Middle-earth",
    "m10": "Magic 2010",
    "m11": "Magic 2011",
    "m12": "Magic 2012",
    "m13": "Magic 2013",
    "m14": "Magic 2014",
    "m15": "Magic 2015",
    "m19": "Core Set 2019",
    "m20": "Core Set 2020",
    "m21": "Core Set 2021",
    "m3c": "Modern Horizons 3 Commander",
    "macr": "Assassin's Creed Minigames",
    "mafr": "Adventures in the Forgotten Realms Minigames",
    "mar": "Marvel Universe",
    "mat": "March of the Machine: The Aftermath",
    "mb2": "Mystery Booster 2",
    "mbro": "The Brothers' War Minigames",
    "mbs": "Mirrodin Besieged",
    "mclb": "Commander Legends: Battle for Baldur's Gate Minigames",
    "md1": "Modern Event Deck 2014",
    "mdmu": "Dominaria United Minigames",
    "me1": "Masters Edition",
    "me2": "Masters Edition II",
    "me3": "Masters Edition III",
    "me4": "Masters Edition IV",
    "med": "Mythic Edition",
    "mgb": "Multiverse Gift Box",
    "mh1": "Modern Horizons",
    "mh2": "Modern Horizons 2",
    "mh3": "Modern Horizons 3",
    "mic": "Midnight Hunt Commander",
    "mid": "Innistrad: Midnight Hunt",
    "mir": "Mirage",
    "mkc": "Murders at Karlov Manor Commander",
    "mkhm": "Kaldheim Minigames",
    "mkm": "Murders at Karlov Manor",
    "mltr": "The Lord of the Rings: Tales of Middle-earth Minigames",
    "mm2": "Modern Masters 2015",
    "mm3": "Modern Masters 2017",
    "mma": "Modern Masters",
    "mmh2": "Modern Horizons 2 Minigames",
    "mmid": "Innistrad: Midnight Hunt Minigames",
    "mmq": "Mercadian Masques",
    "mneo": "Kamigawa: Neon Dynasty Minigames",
    "moc": "March of the Machine Commander",
    "mom": "March of the Machine",
    "mone": "Phyrexia: All Will Be One Minigames",
    "mor": "Morningtide",
    "mp2": "Amonkhet Invocations",
    "mpr": "Magic Player Rewards 2001",
    "mps": "Kaladesh Inventions",
    "mrd": "Mirrodin",
    "msnc": "Streets of New Capenna Minigames",
    "mstx": "Strixhaven: School of Mages Minigames",
    "mul": "Multiverse Legends",
    "mvow": "Innistrad: Crimson Vow Minigames",
    "mznr": "Zendikar Rising Minigames",
    "ncc": "New Capenna Commander",
    "nec": "Neon Dynasty Commander",
    "nem": "Nemesis",
    "neo": "Kamigawa: Neon Dynasty",
    "nph": "New Phyrexia",
    "o90p": "Oversized 90's Promos",
    "oafc": "Forgotten Realms Commander Display Commanders",
    "oana": "Arena New Player Experience Cards",
    "oarc": "Archenemy Schemes",
    "oc13": "Commander 2013 Oversized",
    "oc14": "Commander 2014 Oversized",
    "oc15": "Commander 2015 Oversized",
    "oc16": "Commander 2016 Oversized",
    "oc17": "Commander 2017 Oversized",
    "oc18": "Commander 2018 Oversized",
    "oc19": "Commander 2019 Oversized",
    "oc20": "Commander 2020 Oversized",
    "oc21": "Commander 2021 Display Commanders",
    "ocm1": "Commander's Arsenal Oversized",
    "ocmd": "Commander 2011 Oversized",
    "ody": "Odyssey",
    "oe01": "Archenemy: Nicol Bolas Schemes",
    "ogw": "Oath of the Gatewatch",
    "ohop": "Planechase Planes",
    "olep": "Oversized League Prizes",
    "olgc": "Legacy Championship",
    "omic": "Midnight Hunt Commander Display Commanders",
    "onc": "Phyrexia: All Will Be One Commander",
    "one": "Phyrexia: All Will Be One",
    "ons": "Onslaught",
    "opc2": "Planechase 2012 Planes",
    "opca": "Planechase Anthology Planes",
    "ori": "Magic Origins",
    "otc": "Outlaws of Thunder Junction Commander",
    "otj": "Outlaws of Thunder Junction",
    "otp": "Breaking News",
    "ovnt": "Vintage Championship",
    "ovoc": "Crimson Vow Commander Display Commanders",
    "p02": "Portal Second Age",
    "p03": "Magic Player Rewards 2003",
    "p04": "Magic Player Rewards 2004",
    "p05": "Magic Player Rewards 2005",
    "p06": "Magic Player Rewards 2006",
    "p07": "Magic Player Rewards 2007",
    "p08": "Magic Player Rewards 2008",
    "p09": "Magic Player Rewards 2009",
    "p10": "Magic Player Rewards 2010",
    "p10e": "Tenth Edition Promos",
    "p11": "Magic Player Rewards 2011",
    "p15a": "15th Anniversary Cards",
    "p22": "Judge Gift Cards 2022",
    "p23": "Judge Gift Cards 2023",
    "p2hg": "Two-Headed Giant Tournament",
    "p30a": "30th Anniversary Play Promos",
    "p30h": "30th Anniversary History Promos",
    "p30m": "30th Anniversary Misc Promos",
    "p30t": "30th Anniversary Celebration Tokyo",
    "p5dn": "Fifth Dawn Promos",
    "p8ed": "Eighth Edition Promos",
    "p9ed": "Ninth Edition Promos",
    "pa1": "Pioneer Anthology 1",
    "paer": "Aether Revolt Promos",
    "pafr": "Adventures in the Forgotten Realms Promos",
    "pakh": "Amonkhet Promos",
    "pal00": "Arena League 2000",
    "pal01": "Arena League 2001",
    "pal02": "Arena League 2002",
    "pal03": "Arena League 2003",
    "pal04": "Arena League 2004",
    "pal05": "Arena League 2005",
    "pal06": "Arena League 2006",
    "pal99": "Arena League 1999",
    "pala": "Shards of Alara Promos",
    "palp": "Asia Pacific Land Program",
    "pana": "MTG Arena Promos",
    "papc": "Apocalypse Promos",
    "parb": "Alara Reborn Promos",
    "parl": "Arena League 1996",
    "past": "Astral Cards",
    "pavr": "Avacyn Restored Promos",
    "pbbd": "Battlebond Promos",
    "pbfz": "Battle for Zendikar Promos",
    "pblb": "Bloomburrow Promos",
    "pbng": "Born of the Gods Promos",
    "pbok": "Betrayers of Kamigawa Promos",
    "pbro": "The Brothers' War Promos",
    "pc2": "Planechase 2012",
    "pca": "Planechase Anthology",
    "pcbb": "Cowboy Bebop",
    "pcel": "Celebration Cards",
    "pchk": "Champions of Kamigawa Promos",
    "pclb": "Battle for Baldur's Gate Promos",
    "pcmd": "Commander 2011 Launch Party",
    "pcmp": "Champs and States",
    "pcmr": "Commander Legends Promos",
    "pcns": "Conspiracy Promos",
    "pcon": "Conflux Promos",
    "pcsp": "Coldsnap Promos",
    "pcy": "Prophecy",
    "pd2": "Premium Deck Series: Fire and Lightning",
    "pd3": "Premium Deck Series: Graveborn",
    "pdft": "Aetherdrift Promos",
    "pdgm": "Dragon's Maze Promos",
    "pdis": "Dissension Promos",
    "pdka": "Dark Ascension Promos",
    "pdmu": "Dominaria United Promos",
    "pdom": "Dominaria Promos",
    "pdp10": "Duels of the Planeswalkers 2010 Promos",
    "pdp12": "Duels of the Planeswalkers 2012 Promos",
    "pdp13": "Duels of the Planeswalkers 2013 Promos",
    "pdp14": "Duels of the Planeswalkers 2014 Promos",
    "pdp15": "Duels of the Planeswalkers 2015 Promos",
    "pdrc": "Dragon Con",
    "pdsk": "Duskmourn: House of Horror Promos",
    "pdst": "Darksteel Promos",
    "pdtk": "Dragons of Tarkir Promos",
    "pdtp": "Duels of the Planeswalkers 2009 Promos",
    "peld": "Throne of Eldraine Promos",
    "pelp": "European Land Program",
    "pemn": "Eldritch Moon Promos",
    "peve": "Eventide Promos",
    "pewk": "Eternal Weekend",
    "pexo": "Exodus Promos",
    "pf19": "MagicFest 2019",
    "pf20": "MagicFest 2020",
    "pf23": "MagicFest 2023",
    "pf24": "MagicFest 2024",
    "pf25": "MagicFest 2025",
    "pfdn": "Foundations Promos",
    "pfin": "Final Fantasy Promos",
    "pfrf": "Fate Reforged Promos",
    "pfut": "Future Sight Promos",
    "pgpt": "Guildpact Promos",
    "pgpx": "Grand Prix Promos",
    "pgrn": "Guilds of Ravnica Promos",
    "pgru": "Guru",
    "pgtc": "Gatecrash Promos",
    "ph17": "2017 Heroes of the Realm",
    "ph18": "2018 Heroes of the Realm",
    "ph19": "2019 Heroes of the Realm",
    "ph20": "2020 Heroes of the Realm",
    "ph21": "2021 Heroes of the Realm",
    "ph22": "2022 Heroes of the Realm",
    "phel": "Open the Helvault",
    "phop": "Planechase Promos",
    "phou": "Hour of Devastation Promos",
    "phpr": "HarperPrism Book Promos",
    "phtr": "2016 Heroes of the Realm",
    "phuk": "Hachette UK",
    "pidw": "IDW Comics Inserts",
    "piko": "Ikoria: Lair of Behemoths Promos",
    "pinv": "Invasion Promos",
    "pio": "Pioneer Masters",
    "pip": "Fallout",
    "pisd": "Innistrad Promos",
    "pj21": "Judge Gift Cards 2021",
    "pjas": "Junior APAC Series",
    "pjjt": "Japan Junior Tournament",
    "pjou": "Journey into Nyx Promos",
    "pjsc": "Japan Standard Cup",
    "pjse": "Junior Series Europe",
    "pjud": "Judgment Promos",
    "pkhm": "Kaldheim Promos",
    "pkld": "Kaladesh Promos",
    "pktk": "Khans of Tarkir Promos",
    "pl21": "Year of the Ox 2021",
    "pl22": "Year of the Tiger 2022",
    "pl23": "Year of the Rabbit 2023",
    "pl24": "Year of the Dragon 2024",
    "pl25": "Year of the Snake 2025",
    "plc": "Planar Chaos",
    "plci": "The Lost Caverns of Ixalan Promos",
    "plg20": "Love Your LGS 2020",
    "plg21": "Love Your LGS 2021",
    "plg22": "Love Your LGS 2022",
    "plg24": "Love Your LGS 2024",
    "plg25": "Love Your LGS 2025",
    "plgm": "DCI Legend Membership",
    "plgn": "Legions Promos",
    "plny": "Lunar New Year 2018",
    "plrw": "Lorwyn Promos",
    "pls": "Planeshift",
    "plst": "The List",
    "pltc": "Tales of Middle-earth Deluxe Commander Kit",
    "pltr": "Tales of Middle-earth Promos",
    "pm10": "Magic 2010 Promos",
    "pm11": "Magic 2011 Promos",
    "pm12": "Magic 2012 Promos",
    "pm13": "Magic 2013 Promos",
    "pm14": "Magic 2014 Promos",
    "pm15": "Magic 2015 Promos",
    "pm19": "Core Set 2019 Promos",
    "pm20": "Core Set 2020 Promos",
    "pm21": "Core Set 2021 Promos",
    "pmat": "March of the Machine: The Aftermath Promos",
    "pmbs": "Mirrodin Besieged Promos",
    "pmda": "Magic × Duel Masters Promos",
    "pmei": "Media and Collaboration Promos",
    "pmh1": "Modern Horizons Promos",
    "pmh2": "Modern Horizons 2 Promos",
    "pmh3": "Modern Horizons 3 Promos",
    "pmic": "MicroProse Promos",
    "pmid": "Innistrad: Midnight Hunt Promos",
    "pmkm": "Murders at Karlov Manor Promos",
    "pmmq": "Mercadian Masques Promos",
    "pmoa": "Magic Online Avatars",
    "pmom": "March of the Machine Promos",
    "pmor": "Morningtide Promos",
    "pmps": "Magic Premiere Shop 2005",
    "pmps06": "Magic Premiere Shop 2006",
    "pmps07": "Magic Premiere Shop 2007",
    "pmps08": "Magic Premiere Shop 2008",
    "pmps09": "Magic Premiere Shop 2009",
    "pmps10": "Magic Premiere Shop 2010",
    "pmps11": "Magic Premiere Shop 2011",
    "pmrd": "Mirrodin Promos",
    "pnat": "Nationals Promos",
    "pncc": "New Capenna Commander Promos",
    "pnem": "Nemesis Promos",
    "pneo": "Kamigawa: Neon Dynasty Promos",
    "pnph": "New Phyrexia Promos",
    "pody": "Odyssey Promos",
    "pogw": "Oath of the Gatewatch Promos",
    "pone": "Phyrexia: All Will Be One Promos",
    "pons": "Onslaught Promos",
    "por": "Portal",
    "pori": "Magic Origins Promos",
    "potj": "Outlaws of Thunder Junction Promos",
    "ppc1": "M15 Prerelease Challenge",
    "ppcy": "Prophecy Promos",
    "pplc": "Planar Chaos Promos",
    "ppls": "Planeshift Promos",
    "ppp1": "M20 Promo Packs",
    "ppro": "Pro Tour Promos",
    "pptk": "Portal: Three Kingdoms Promos",
    "pr2": "Magic Player Rewards 2002",
    "pr23": "Regional Championship Qualifiers 2023",
    "prav": "Ravnica: City of Guilds Promos",
    "prcq": "Regional Championship Qualifiers 2022",
    "pred": "Redemption Program",
    "prix": "Rivals of Ixalan Promos",
    "prm": "Magic Online Promos",
    "prna": "Ravnica Allegiance Promos",
    "proe": "Rise of the Eldrazi Promos",
    "prtr": "Return to Ravnica Promos",
    "prw2": "RNA Ravnica Weekend",
    "prwk": "GRN Ravnica Weekend",
    "ps11": "Salvat 2011",
    "ps14": "San Diego Comic-Con 2014",
    "ps15": "San Diego Comic-Con 2015",
    "ps16": "San Diego Comic-Con 2016",
    "ps17": "San Diego Comic-Con 2017",
    "ps18": "San Diego Comic-Con 2018",
    "ps19": "San Diego Comic-Con 2019",
    "psal": "Salvat 2005",
    "pscg": "Scourge Promos",
    "psdc": "San Diego Comic-Con 2013",
    "psdg": "Sega Dreamcast Cards",
    "pshm": "Shadowmoor Promos",
    "psnc": "Streets of New Capenna Promos",
    "psoi": "Shadows over Innistrad Promos",
    "psok": "Saviors of Kamigawa Promos",
    "psom": "Scars of Mirrodin Promos",
    "pspl": "Spotlight Series",
    "pss1": "BFZ Standard Series",
    "pss2": "XLN Standard Showdown",
    "pss3": "M19 Standard Showdown",
    "pss4": "MKM Standard Showdown",
    "pss5": "FIN Standard Showdown",
    "pssc": "Secret Lair Showcase Planes",
    "psth": "Stronghold Promos",
    "pstx": "Strixhaven: School of Mages Promos",
    "psus": "Junior Super Series",
    "psvc": "Summer Vacation Promos 2022",
    "ptbro": "The Brothers' War Southeast Asia Tokens",
    "ptc": "Pro Tour Collector Set",
    "ptdm": "Tarkir: Dragonstorm Promos",
    "ptdmu": "Dominaria United Southeast Asia Tokens",
    "ptg": "Ponies: The Galloping",
    "pthb": "Theros Beyond Death Promos",
    "pths": "Theros Promos",
    "ptk": "Portal Three Kingdoms",
    "ptkdf": "Tarkir Dragonfury",
    "ptmp": "Tempest Promos",
    "ptor": "Torment Promos",
    "ptsnc": "Streets of New Capenna Southeast Asia Tokens",
    "ptsp": "Time Spiral Promos",
    "ptsr": "Time Spiral Remastered Promos",
    "puds": "Urza's Destiny Promos",
    "pulg": "Urza's Legacy Promos",
    "puma": "Ultimate Box Topper",
    "punh": "Unhinged Promos",
    "purl": "URL/Convention Promos",
    "pusg": "Urza's Saga Promos",
    "pust": "Unstable Promos",
    "pvan": "Vanguard Series",
    "pvow": "Innistrad: Crimson Vow Promos",
    "pw11": "Wizards Play Network 2011",
    "pw12": "Wizards Play Network 2012",
    "pw21": "Wizards Play Network 2021",
    "pw22": "Wizards Play Network 2022",
    "pw23": "Wizards Play Network 2023",
    "pw24": "Wizards Play Network 2024",
    "pw25": "Wizards Play Network 2025",
    "pwar": "War of the Spark Promos",
    "pwcs": "Planeswalker Championship Promos",
    "pwoe": "Wilds of Eldraine Promos",
    "pwor": "World Championship Promos",
    "pwos": "Wizards of the Coast Online Store",
    "pwwk": "Worldwake Promos",
    "pxln": "Ixalan Promos",
    "pxtc": "XLN Treasure Chest",
    "pz1": "Legendary Cube Prize Pack",
    "pz2": "Treasure Chest",
    "pzen": "Zendikar Promos",
    "pznr": "Zendikar Rising Promos",
    "q06": "Pioneer Challenger Decks 2021",
    "q07": "Challenger Decks 2022",
    "rav": "Ravnica: City of Guilds",
    "ren": "Renaissance",
    "rex": "Jurassic World Collection",
    "rfin": "Final Fantasy Regional Promos",
    "rin": "Rinascimento",
    "rix": "Rivals of Ixalan",
    "rna": "Ravnica Allegiance",
    "roe": "Rise of the Eldrazi",
    "rqs": "Rivals Quick Start Set",
    "rtr": "Return to Ravnica",
    "rvr": "Ravnica Remastered",
    "s00": "Starter 2000",
    "s99": "Starter 1999",
    "sbro": "The Brothers' War Substitute Cards",
    "scd": "Starter Commander Decks",
    "scg": "Scourge",
    "sch": "Store Championships",
    "shm": "Shadowmoor",
    "sir": "Shadows over Innistrad Remastered",
    "sis": "Shadows of the Past",
    "skhm": "Kaldheim Substitute Cards",
    "slc": "Secret Lair 30th Anniversary Countdown Kit",
    "slci": "The Lost Caverns of Ixalan Substitute Cards",
    "sld": "Secret Lair Drop",
    "slp": "Secret Lair Showdown",
    "slu": "Secret Lair: Ultimate Edition",
    "slx": "Universes Within",
    "smh3": "Modern Horizons 3 Substitute Cards",
    "smid": "Innistrad: Midnight Hunt Substitute Cards",
    "smom": "March of the Machine Substitute Cards",
    "snc": "Streets of New Capenna",
    "sneo": "Kamigawa: Neon Dynasty Substitute Cards",
    "soi": "Shadows over Innistrad",
    "sok": "Saviors of Kamigawa",
    "som": "Scars of Mirrodin",
    "spe": "Marvel's Spider-Man Eternal",
    "spg": "Special Guests",
    "spm": "Marvel's Spider-Man",
    "ss1": "Signature Spellbook: Jace",
    "ss2": "Signature Spellbook: Gideon",
    "ss3": "Signature Spellbook: Chandra",
    "sstx": "Strixhaven: School of Mages Substitute Cards",
    "sta": "Strixhaven Mystical Archive",
    "sth": "Stronghold",
    "stx": "Strixhaven: School of Mages",
    "sum": "Summer Magic / Edgar",
    "sunf": "Unfinity Sticker Sheets",
    "svow": "Innistrad: Crimson Vow Substitute Cards",
    "sznr": "Zendikar Rising Substitute Cards",
    "t10e": "Tenth Edition Tokens",
    "t2x2": "Double Masters 2022 Tokens",
    "t2xm": "Double Masters Tokens",
    "t30a": "30th Anniversary Tokens",
    "t40k": "Warhammer 40,000 Tokens",
    "ta25": "Masters 25 Tokens",
    "tacr": "Assassin's Creed Tokens",
    "taer": "Aether Revolt Tokens",
    "tafc": "Forgotten Realms Commander Tokens",
    "tafr": "Adventures in the Forgotten Realms Tokens",
    "takh": "Amonkhet Tokens",
    "tala": "Shards of Alara Tokens",
    "tarb": "Alara Reborn Tokens",
    "tavr": "Avacyn Restored Tokens",
    "tbbd": "Battlebond Tokens",
    "tbfz": "Battle for Zendikar Tokens",
    "tbig": "The Big Score Tokens",
    "tblb": "Bloomburrow Tokens",
    "tblc": "Bloomburrow Commander Tokens",
    "tbng": "Born of the Gods Tokens",
    "tbot": "Transformers Tokens",
    "tbrc": "The Brothers' War Commander Tokens",
    "tbro": "The Brothers' War Tokens",
    "tbth": "Battle the Horde",
    "tc14": "Commander 2014 Tokens",
    "tc15": "Commander 2015 Tokens",
    "tc16": "Commander 2016 Tokens",
    "tc17": "Commander 2017 Tokens",
    "tc18": "Commander 2018 Tokens",
    "tc19": "Commander 2019 Tokens",
    "tc20": "Commander 2020 Tokens",
    "tc21": "Commander 2021 Tokens",
    "tclb": "Battle for Baldur's Gate Tokens",
    "tcm2": "Commander Anthology Volume II Tokens",
    "tcma": "Commander Anthology Tokens",
    "tcmm": "Commander Masters Tokens",
    "tcmr": "Commander Legends Tokens",
    "tcn2": "Conspiracy: Take the Crown Tokens",
    "tcns": "Conspiracy Tokens",
    "tcon": "Conflux Tokens",
    "td0": "Magic Online Theme Decks",
    "td2": "Duel Decks: Mirrodin Pure vs. New Phyrexia",
    "tdag": "Defeat a God",
    "tdc": "Tarkir: Dragonstorm Commander",
    "tdd1": "Duel Decks: Elves vs. Goblins Tokens",
    "tdd2": "Duel Decks: Jace vs. Chandra Tokens",
    "tddc": "Duel Decks: Divine vs. Demonic Tokens",
    "tddd": "Duel Decks: Garruk vs. Liliana Tokens",
    "tdde": "Duel Decks: Phyrexia vs. the Coalition Tokens",
    "tddf": "Duel Decks: Elspeth vs. Tezzeret Tokens",
    "tddg": "Duel Decks: Knights vs. Dragons Tokens",
    "tddh": "Duel Decks: Ajani vs. Nicol Bolas Tokens",
    "tddi": "Duel Decks: Venser vs. Koth Tokens",
    "tddj": "Duel Decks: Izzet vs. Golgari Tokens",
    "tddk": "Duel Decks: Sorin vs. Tibalt Tokens",
    "tddl": "Duel Decks: Heroes vs. Monsters Tokens",
    "tddm": "Duel Decks: Jace vs. Vraska Tokens",
    "tdds": "Duel Decks: Mind vs. Might Tokens",
    "tddt": "Duel Decks: Merfolk vs. Goblins Tokens",
    "tddu": "Duel Decks: Elves vs. Inventors Tokens",
    "tdft": "Aetherdrift Tokens",
    "tdgm": "Dragon's Maze Tokens",
    "tdka": "Dark Ascension Tokens",
    "tdm": "Tarkir: Dragonstorm",
    "tdmc": "Dominaria United Commander Tokens",
    "tdmr": "Dominaria Remastered Tokens",
    "tdmu": "Dominaria United Tokens",
    "tdom": "Dominaria Tokens",
    "tdrc": "Aetherdrift Commander Tokens",
    "tdsc": "Duskmourn Commander Tokens",
    "tdsk": "Duskmourn: House of Horror Tokens",
    "tdtk": "Dragons of Tarkir Tokens",
    "tdvd": "Duel Decks Anthology: Divine vs. Demonic Tokens",
    "te01": "Archenemy: Nicol Bolas Tokens",
    "teld": "Throne of Eldraine Tokens",
    "tema": "Eternal Masters Tokens",
    "temn": "Eldritch Moon Tokens",
    "teoc": "Edge of Eternities Commander Tokens",
    "teoe": "Edge of Eternities Tokens",
    "teve": "Eventide Tokens",
    "tevg": "Duel Decks Anthology: Elves vs. Goblins Tokens",
    "tfdn": "Foundations Tokens",
    "tfic": "Final Fantasy Commander Tokens",
    "tfin": "Final Fantasy Tokens",
    "tfrf": "Fate Reforged Tokens",
    "tfth": "Face the Hydra",
    "tgk1": "GRN Guild Kit Tokens",
    "tgk2": "RNA Guild Kit Tokens",
    "tgn2": "Game Night 2019 Tokens",
    "tgn3": "Game Night: Free-for-All Tokens",
    "tgrn": "Guilds of Ravnica Tokens",
    "tgtc": "Gatecrash Tokens",
    "tgvl": "Duel Decks Anthology: Garruk vs. Liliana Tokens",
    "thb": "Theros Beyond Death",
    "thou": "Hour of Devastation Tokens",
    "thp1": "Theros Hero's Path",
    "thp2": "Born of the Gods Hero's Path",
    "thp3": "Journey into Nyx Hero's Path",
    "ths": "Theros",
    "tiko": "Ikoria: Lair of Behemoths Tokens",
    "tima": "Iconic Masters Tokens",
    "tinr": "Innistrad Remastered Tokens",
    "tisd": "Innistrad Tokens",
    "tjou": "Journey into Nyx Tokens",
    "tjvc": "Duel Decks Anthology: Jace vs. Chandra Tokens",
    "tkhc": "Kaldheim Commander Tokens",
    "tkhm": "Kaldheim Tokens",
    "tkld": "Kaladesh Tokens",
    "tktk": "Khans of Tarkir Tokens",
    "tla": "Avatar: The Last Airbender",
    "tlcc": "The Lost Caverns of Ixalan Commander Tokens",
    "tlci": "The Lost Caverns of Ixalan Tokens",
    "tlrw": "Lorwyn Tokens",
    "tltc": "Tales of Middle-earth Commander Tokens",
    "tltr": "Tales of Middle-earth Tokens",
    "tm10": "Magic 2010 Tokens",
    "tm11": "Magic 2011 Tokens",
    "tm12": "Magic 2012 Tokens",
    "tm13": "Magic 2013 Tokens",
    "tm14": "Magic 2014 Tokens",
    "tm15": "Magic 2015 Tokens",
    "tm19": "Core Set 2019 Tokens",
    "tm20": "Core Set 2020 Tokens",
    "tm21": "Core Set 2021 Tokens",
    "tm3c": "Modern Horizons 3 Commander Tokens",
    "tmbs": "Mirrodin Besieged Tokens",
    "tmd1": "Modern Event Deck 2014 Tokens",
    "tmed": "Mythic Edition Tokens",
    "tmh1": "Modern Horizons Tokens",
    "tmh2": "Modern Horizons 2 Tokens",
    "tmh3": "Modern Horizons 3 Tokens",
    "tmic": "Midnight Hunt Commander Tokens",
    "tmid": "Innistrad: Midnight Hunt Tokens",
    "tmkc": "Murders at Karlov Manor Commander Tokens",
    "tmkm": "Murders at Karlov Manor Tokens",
    "tmm2": "Modern Masters 2015 Tokens",
    "tmm3": "Modern Masters 2017 Tokens",
    "tmma": "Modern Masters Tokens",
    "tmoc": "March of the Machine Commander Tokens",
    "tmom": "March of the Machine Tokens",
    "tmor": "Morningtide Tokens",
    "tmp": "Tempest",
    "tmul": "Multiverse Legends Tokens",
    "tncc": "New Capenna Commander Tokens",
    "tnec": "Neon Dynasty Commander Tokens",
    "tneo": "Kamigawa: Neon Dynasty Tokens",
    "tnph": "New Phyrexia Tokens",
    "togw": "Oath of the Gatewatch Tokens",
    "tonc": "Phyrexia: All Will Be One Commander Tokens",
    "tone": "Phyrexia: All Will Be One Tokens",
    "tor": "Torment",
    "tori": "Magic Origins Tokens",
    "totc": "Outlaws of Thunder Junction Commander Tokens",
    "totj": "Outlaws of Thunder Junction Tokens",
    "totp": "Breaking News Tokens",
    "tpca": "Planechase Anthology Tokens",
    "tpip": "Fallout Tokens",
    "tpr": "Tempest Remastered",
    "trex": "Jurassic World Collection Tokens",
    "trix": "Rivals of Ixalan Tokens",
    "trna": "Ravnica Allegiance Tokens",
    "troe": "Rise of the Eldrazi Tokens",
    "trtr": "Return to Ravnica Tokens",
    "trvr": "Ravnica Remastered Tokens",
    "tsb": "Time Spiral Timeshifted",
    "tscd": "Starter Commander Deck Tokens",
    "tshm": "Shadowmoor Tokens",
    "tsnc": "Streets of New Capenna Tokens",
    "tsoi": "Shadows over Innistrad Tokens",
    "tsom": "Scars of Mirrodin Tokens",
    "tsp": "Time Spiral",
    "tspm": "Marvel's Spider-Man Tokens",
    "tsr": "Time Spiral Remastered",
    "tstx": "Strixhaven: School of Mages Tokens",
    "ttdc": "Tarkir: Dragonstorm Commander Tokens",
    "ttdm": "Tarkir: Dragonstorm Tokens",
    "tthb": "Theros Beyond Death Tokens",
    "tths": "Theros Tokens",
    "ttsr": "Time Spiral Remastered Tokens",
    "tugl": "Unglued Tokens",
    "tuma": "Ultimate Masters Tokens",
    "tund": "Unsanctioned Tokens",
    "tunf": "Unfinity Tokens",
    "tust": "Unstable Tokens",
    "tvoc": "Crimson Vow Commander Tokens",
    "tvow": "Innistrad: Crimson Vow Tokens",
    "twar": "War of the Spark Tokens",
    "twho": "Doctor Who Tokens",
    "twoc": "Wilds of Eldraine Commander Tokens",
    "twoe": "Wilds of Eldraine Tokens",
    "twwk": "Worldwake Tokens",
    "txln": "Ixalan Tokens",
    "tzen": "Zendikar Tokens",
    "tznc": "Zendikar Rising Commander Tokens",
    "tznr": "Zendikar Rising Tokens",
    "uds": "Urza's Destiny",
    "ugin": "Ugin's Fate",
    "ugl": "Unglued",
    "ulg": "Urza's Legacy",
    "ulst": "The List (Unfinity Foil Edition)",
    "uma": "Ultimate Masters",
    "und": "Unsanctioned",
    "unf": "Unfinity",
    "unh": "Unhinged",
    "unk": "Unknown Event",
    "usg": "Urza's Saga",
    "ust": "Unstable",
    "v09": "From the Vault: Exiled",
    "v10": "From the Vault: Relics",
    "v11": "From the Vault: Legends",
    "v12": "From the Vault: Realms",
    "v13": "From the Vault: Twenty",
    "v14": "From the Vault: Annihilation",
    "v15": "From the Vault: Angels",
    "v16": "From the Vault: Lore",
    "v17": "From the Vault: Transform",
    "vis": "Visions",
    "vma": "Vintage Masters",
    "voc": "Crimson Vow Commander",
    "vow": "Innistrad: Crimson Vow",
    "w16": "Welcome Deck 2016",
    "w17": "Welcome Deck 2017",
    "war": "War of the Spark",
    "wc00": "World Championship Decks 2000",
    "wc01": "World Championship Decks 2001",
    "wc02": "World Championship Decks 2002",
    "wc03": "World Championship Decks 2003",
    "wc04": "World Championship Decks 2004",
    "wc97": "World Championship Decks 1997",
    "wc98": "World Championship Decks 1998",
    "wc99": "World Championship Decks 1999",
    "wdmu": "DMU Japanese Promo Tokens",
    "who": "Doctor Who",
    "wmc": "World Magic Cup Qualifiers",
    "wmkm": "MKM Japanese Promo Tokens",
    "wmom": "MOM Japanese Promo Tokens",
    "woc": "Wilds of Eldraine Commander",
    "woe": "Wilds of Eldraine",
    "wone": "ONE Japanese Promo Tokens",
    "wot": "Wilds of Eldraine: Enchanting Tales",
    "wth": "Weatherlight",
    "wwk": "Worldwake",
    "wwoe": "WOE Japanese Promo Tokens",
    "xana": "Arena New Player Experience Extras",
    "xln": "Ixalan",
    "yblb": "Alchemy: Bloomburrow",
    "ybro": "Alchemy: The Brothers' War",
    "ydft": "Alchemy: Aetherdrift",
    "ydmu": "Alchemy: Dominaria",
    "ydsk": "Alchemy: Duskmourn",
    "ylci": "Alchemy: Ixalan",
    "ymid": "Alchemy: Innistrad",
    "ymkm": "Alchemy: Murders at Karlov Manor ",
    "yneo": "Alchemy: Kamigawa",
    "yone": "Alchemy: Phyrexia",
    "yotj": "Alchemy: Outlaws of Thunder Junction",
    "ysnc": "Alchemy: New Capenna",
    "ytdm": "Alchemy: Tarkir",
    "ywoe": "Alchemy: Wilds of Eldraine",
    "zen": "Zendikar",
    "znc": "Zendikar Rising Commander",
    "zne": "Zendikar Rising Expeditions",
    "znr": "Zendikar Rising",
}

MTG_KEYWORDS = {
    "Deathtouch": "Any amount of damage this deals to a creature is enough to destroy it.",
    "Defender": "This creature can't attack.",
    "Double Strike": "This creature deals both first-strike and regular combat damage.",
    "Enchant": "This Aura can only be attached to a specified type of permanent.",
    "Equip": "Attach this Equipment to a creature you control by paying the equip cost.",
    "First Strike": "This creature deals combat damage before creatures without first strike.",
    "Flash": "You may cast this spell any time you could cast an instant.",
    "Flying": "This creature can't be blocked except by creatures with flying or reach.",
    "Haste": "This creature can attack and {T} as soon as it comes under your control.",
    "Hexproof": "This permanent can't be the target of spells or abilities your opponents control.",
    "Indestructible": "Effects that say 'destroy' don't destroy this creature. It can't be destroyed by damage.",
    "Lifelink": "Damage dealt by this creature also causes you to gain that much life.",
    "Menace": "This creature can't be blocked except by two or more creatures.",
    "Prowess": "Whenever you cast a noncreature spell, this creature gets +1/+1 until end of turn.",
    "Reach": "This creature can block creatures with flying.",
    "Trample": "Excess damage this creature deals to blockers is dealt to the defending player or planeswalker.",
    "Vigilance": "Attacking doesn't cause this creature to tap.",
    "Shroud": "This permanent can't be the target of any spells or abilities.",
    "Protection": "This permanent can't be targeted, dealt damage, enchanted, or blocked by anything of the specified quality.",
    "Flashback": "You may cast this card from your graveyard for its flashback cost. Then exile it.",
    "Cycling": "Pay the cycling cost and discard this card to draw a card.",
    "Morph": "You may cast this card face down as a 2/2 creature for {3}. Turn it face up any time for its morph cost.",
    "Persist": "When this creature dies, if it had no -1/-1 counters on it, return it to the battlefield under its owner's control with a -1/-1 counter on it.",
    "Undying": "When this creature dies, if it had no +1/+1 counters on it, return it to the battlefield under its owner's control with a +1/+1 counter on it.",
    "Scry": "Look at the top card(s) of your library, then put any number of them on the bottom of your library and the rest on top in any order.",
    "Cascade": "When you cast this spell, exile cards from the top of your library until you exile a nonland card that costs less. You may cast it without paying its mana cost.",
    "Convoke": "Your creatures can help cast this spell. Each creature you tap while casting this spell pays for {1} or one mana of that creature's color.",
    "Delve": "Each card you exile from your graveyard while casting this spell pays for {1}.",
    "Evoke": "You may cast this spell for its evoke cost. If you do, it's sacrificed when it enters the battlefield.",
    "Kicker": "You may pay an additional cost as you cast this spell to gain an additional effect.",
    "Landwalk": "This creature can't be blocked as long as defending player controls a land of the specified type.",
    "Modular": "This creature enters the battlefield with a number of +1/+1 counters on it. When it dies, you may put its +1/+1 counters on target artifact creature.",
    "Ninjutsu": "Pay the ninjutsu cost and return an unblocked attacker you control to hand: Put this card onto the battlefield from your hand tapped and attacking.",
    "Overload": "You may cast this spell for its overload cost. If you do, change its text by replacing all instances of 'target' with 'each.'",
    "Phasing": "This permanent phases in and out of play, meaning it alternates between being on the battlefield and being treated as though it doesn't exist.",
    "Provoke": "When this creature attacks, you may have target creature defending player controls untap and block it if able.",
    "Rampage": "Whenever this creature becomes blocked, it gets +X/+X until end of turn for each creature blocking it beyond the first.",
    "Rebound": "If you cast this spell from your hand, exile it as it resolves. At the beginning of your next upkeep, you may cast it from exile without paying its mana cost.",
    "Retrace": "You may cast this card from your graveyard by discarding a land card in addition to paying its other costs.",
    "Scavenge": "Exile this card from your graveyard: Put a number of +1/+1 counters equal to this card's power on target creature. Scavenge only as a sorcery.",
    "Split Second": "As long as this spell is on the stack, players can't cast spells or activate abilities that aren't mana abilities.",
    "Storm": "When you cast this spell, copy it for each spell cast before it this turn. You may choose new targets for the copies.",
    "Suspend": "Rather than cast this card from your hand, you may pay its suspend cost and exile it with a number of time counters on it. At the beginning of your upkeep, remove a time counter. When the last is removed, cast it without paying its mana cost.",
    "Transmute": "Pay the transmute cost and discard this card: Search your library for a card with the same converted mana cost, reveal it, and put it into your hand. Then shuffle your library. Transmute only as a sorcery.",
    "Unearth": "Return this card from your graveyard to the battlefield. It gains haste. Exile it at the beginning of the next end step or if it would leave the battlefield. Unearth only as a sorcery.",
    "Wither": "This deals damage to creatures in the form of -1/-1 counters.",
    "Affinity": "This spell costs {1} less to cast for each permanent you control of the specified type.",
    "Annihilator": "Whenever this creature attacks, defending player sacrifices a number of permanents equal to the annihilator number.",
    "Bestow": "If you cast this card for its bestow cost, it's an Aura spell with enchant creature. It becomes a creature again if it's not attached to a creature.",
    "Bloodthirst": "If an opponent was dealt damage this turn, this creature enters the battlefield with additional +1/+1 counters.",
    "Bushido": "When this blocks or becomes blocked, it gets +X/+X until end of turn.",
    "Champion": "When this enters the battlefield, sacrifice it unless you exile another creature you control of the specified type. When this leaves the battlefield, that card returns to the battlefield.",
    "Cipher": "Then you may exile this spell card encoded on a creature you control. Whenever that creature deals combat damage to a player, its controller may cast a copy of the encoded card without paying its mana cost.",
    "Dredge": "If you would draw a card, you may instead put a number of cards from the top of your library into your graveyard and return this card from your graveyard to your hand.",
    "Entwine": "You may choose both modes of a spell with entwine if you pay the entwine cost.",
    "Epic": "For the rest of the game, you can't cast spells. At the beginning of each of your upkeeps, copy this spell except for its epic ability.",
    "Exalted": "Whenever a creature you control attacks alone, that creature gets +1/+1 until end of turn.",
    "Exploit": "When this creature enters the battlefield, you may sacrifice a creature. If you do, it gains an additional effect.",
    "Extort": "Whenever you cast a spell, you may pay {W/B}. If you do, each opponent loses 1 life and you gain that much life.",
    "Fading": "This permanent enters the battlefield with a number of fade counters. At the beginning of your upkeep, remove a fade counter. If you can't, sacrifice it.",
    "Fear": "This creature can't be blocked except by artifact creatures and/or black creatures.",
    "Forecast": "During your upkeep, you may reveal this card from your hand and pay its forecast cost. If you do, an effect occurs.",
    "Graft": "This creature enters the battlefield with a number of +1/+1 counters. Whenever another creature enters the battlefield, you may move a +1/+1 counter from this creature onto it.",
    "Haunt": "When this card is put into a graveyard, exile it haunting target creature. When that creature dies, you may apply an effect.",
    "Hideaway": "This land enters the battlefield tapped. When it does, look at the top four cards of your library, exile one face down, then put the rest on the bottom of your library. You may play the exiled card without paying its mana cost if a certain condition is met.",
    "Infect": "This creature deals damage to creatures in the form of -1/-1 counters and to players in the form of poison counters.",
    "Intimidate": "This creature can't be blocked except by artifact creatures and/or creatures that share a color with it.",
    "Madness": "If you discard this card, you may cast it for its madness cost instead of putting it into your graveyard.",
    "Miracle": "You may cast this card for its miracle cost when you draw it if it's the first card you drew this turn.",
    "Modular": "This creature enters the battlefield with a number of +1/+1 counters. When it dies, you may put its +1/+1 counters on target artifact creature.",
    "Myriad": "Whenever this creature attacks, for each opponent other than defending player, you may create a token that's a copy of this creature that's tapped and attacking that opponent or a planeswalker they control. Exile the tokens at end of combat.",
    "Outlast": "Pay the outlast cost and tap this creature: Put a +1/+1 counter on it. Outlast only as a sorcery.",
    "Overload": "You may cast this spell for its overload cost. If you do, change its text by replacing all instances of 'target' with 'each.'",
    "Landfall": "Whenever a land enters the battlefield under your control, [effect].",
    "Partner with": "When this creature enters the battlefield, target player may put [partner name] into their hand from their library, then shuffle.",
    "Partner": "You can have two commanders if both have partner.",
    "Metalcraft": "This ability functions as long as you control three or more artifacts.",
    "Islandwalk": "This creature can't be blocked as long as defending player controls an Island.",
    "Treasure": "Artifact token with 'Tap, Sacrifice this artifact: Add one mana of any color.'",
    "Soulbond": "You may pair this creature with another unpaired creature when either enters the battlefield. They remain paired as long as you control both.",
    "Crew": "Tap any number of creatures you control with total power N or more: This Vehicle becomes an artifact creature until end of turn.",
    "Renown": "When this creature deals combat damage to a player, if it isn't renowned, put N +1/+1 counters on it and it becomes renowned.",
    "Escape": "You may cast this card from your graveyard for its escape cost. (Exile N other cards from your graveyard.)",
    "First strike": "This creature deals combat damage before creatures without first strike.",
    "Mill": "Put the top N cards of target player's library into their graveyard.",
    "Encore": "Exile this card from your graveyard: For each opponent, create a token copy that attacks that opponent this turn if able. They gain haste. Sacrifice them at the beginning of the next end step.",
    "Goad": "Until your next turn, that creature attacks each combat if able and attacks a player other than you if able.",
    "Hexproof from": "This permanent can't be the target of [specified quality] spells or abilities your opponents control.",
    "Umbra armor": "If enchanted creature would be destroyed, instead remove all damage from it and destroy this Aura.",
    "Fight": "Each creature deals damage equal to its power to the other.",
    "Reconfigure": "Attach to target creature you control; or unattach from a creature. Reconfigure only as a sorcery.",
    "Afflict": "Whenever this creature becomes blocked, defending player loses N life.",
    "Melee": "Whenever this creature attacks, it gets +1/+1 until end of turn for each opponent you attacked this combat.",
    "Living weapon": "When this Equipment enters the battlefield, create a 0/0 black Germ creature token, then attach this to it.",
    "Exhaust": "This ability is not a standard MTG keyword.",
    "Echo": "At the beginning of your upkeep, if this permanent came under your control since the beginning of your last upkeep, sacrifice it unless you pay its echo cost.",
    "Ward": "Whenever this permanent becomes the target of a spell or ability an opponent controls, counter it unless that player pays N.",
    "Multikicker": "You may pay an additional [cost] any number of times as you cast this spell.",
    "Split second": "As long as this spell is on the stack, players can't cast spells or activate abilities that aren't mana abilities.",
    "Improvise": "Your artifacts can help cast this spell. Each artifact you tap after you're done activating mana abilities pays for {1}.",
    "Monstrosity": "If this creature isn't monstrous, put N +1/+1 counters on it and it becomes monstrous.",
    "Plot": "You may pay [cost] and exile this card from your hand. Cast it as a sorcery on a later turn without paying its mana cost.",
    "Spree": "Choose one or more modes. As an additional cost to cast this spell, pay the costs associated with those modes.",
    "Changeling": "This card is every creature type.",
    "Gift": "You may cast this spell for its gift cost. If you do, [effect].",
    "Collect evidence": "Exile cards from your graveyard with total mana value N or greater.",
    "Surveil": "Look at the top N cards of your library. Put any number into your graveyard and the rest on top in any order.",
    "Investigate": "Create a Clue token. (It's an artifact with '2, Sacrifice this artifact: Draw a card.')",
    "Dethrone": "Whenever this creature attacks the player with the most life or tied for most life, put a +1/+1 counter on it.",
    "Food": "A Food is an artifact with '2, T: Sacrifice this artifact: You gain 3 life.'",
    "Disguise": "You may cast this card face down as a 2/2 creature with ward 2. Turn it face up any time for its disguise cost.",
    "Mentor": "Whenever this creature attacks, put a +1/+1 counter on target attacking creature with lesser power.",
    "Offspring": "When this creature dies, create a token that's a copy of it, except it's 1/1 and has no abilities.",
    "Mobilize": "Tap this creature: Untap another target creature.",
    "Suspect": "A suspected creature has menace and can't block.",
    "Double strike": "This creature deals both first-strike and regular combat damage.",
    "Proliferate": "Choose any number of permanents and/or players with counters. Give each another counter of a kind already there.",
    "Saddle": "Tap any number of creatures you control with total power N or more: This Mount becomes a creature until end of turn.",
    "Valiant": "Whenever this creature attacks alone, it gets +1/+1 until end of turn.",
    "Fabricate": "When this creature enters the battlefield, put N +1/+1 counters on it or create N 1/1 colorless Servo artifact creature tokens.",
    "Forage": "You may exile a card from your graveyard. If you do, [effect].",
    "Flanking": "Whenever a creature without flanking blocks this creature, the blocking creature gets -1/-1 until end of turn.",
    "Threshold": "As long as seven or more cards are in your graveyard, [effect].",
    "Flurry": "Whenever you cast a spell, [effect].",
    "Battle Cry": "Whenever this creature attacks, each other attacking creature gets +1/+0 until end of turn.",
    "Harmonize": "Draw three cards.",
    "Cloak": "Put the card onto the battlefield face down as a 2/2 creature with ward 2. Turn it face up any time for its mana cost if it's a creature card.",
    "Landcycling": "Pay [cost], discard this card: Search your library for a land card, reveal it, put it into your hand, then shuffle.",
    "Basic landcycling": "Pay [cost], discard this card: Search your library for a basic land card, reveal it, put it into your hand, then shuffle.",
    "Typecycling": "Pay [cost], discard this card: Search your library for a card of the specified type, reveal it, put it into your hand, then shuffle.",
    "Manifest": "Put the card onto the battlefield face down as a 2/2 creature. Turn it face up any time for its mana cost if it's a creature card.",
    "Lieutenant": "As long as you control your commander, [effect].",
    "Magecraft": "Whenever you cast or copy an instant or sorcery spell, [effect].",
    "Tempting offer": "When this spell resolves, each opponent may choose to copy it. For each opponent who does, [effect].",
    "Council's dilemma": "When this spell resolves, each player votes for one of two options. Then, [effect based on votes].",
    "Demonstrate": "When you cast this spell, you may copy it. If you do, choose an opponent to also copy it. The copies may choose new targets.",
    "Eternalize": "Pay [cost], exile this card from your graveyard: Create a token that's a copy of it, except it's a 4/4 black Zombie with no mana cost.",
    "Exert": "When this creature attacks, you may choose to exert it. If you do, it won't untap during your next untap step, and [effect].",
    "Riot": "This creature enters the battlefield with your choice of a +1/+1 counter or haste.",
    "Connive": "Draw a card, then discard a card. If you discarded a nonland card, put a +1/+1 counter on this creature.",
    "Channel": "Pay [cost], discard this card: [effect].",
    "Shadow": "This creature can block or be blocked only by creatures with shadow.",
    "Enrage": "A triggered ability that activates when the creature is dealt damage, providing beneficial effects.",
    "Corrupted": "An ability word that grants enhanced effects if an opponent has three or more poison counters.",
    "Role token": "Colorless Aura enchantment tokens that attach to creatures, granting specific abilities; only one Role per creature per player.",
    "Discover": "A keyword action where you exile cards from the top of your library until you exile a nonland card with mana value X or less. You may cast that card without paying its mana cost or put it into your hand.",
    "Eerie": "A triggered ability that activates whenever an enchantment enters the battlefield under your control or when you fully unlock a Room.",
    "Addendum": "An ability word that provides additional effects if the spell is cast during your main phase.",
    "Explore": "A keyword action where you reveal the top card of your library. If it's a land, put it into your hand; otherwise, put a +1/+1 counter on the creature and choose to keep the card on top or put it into your graveyard.",
    "Compleated": "A keyword ability allowing Planeswalkers to be cast using Phyrexian mana; if life is paid, the Planeswalker enters with fewer loyalty counters.",
    "Prototype": "A keyword ability that allows you to cast an artifact creature card for an alternative cost, resulting in a creature with different power, toughness, and mana cost but retaining its abilities.",
    "Assist": "A keyword ability that allows another player to help pay for the generic mana portion of a spell's cost.",
    "Transform": "A keyword action that turns a double-faced card to its other face, changing its characteristics.",
    "Descend": "A mechanic that refers to putting a permanent card into your graveyard from anywhere, triggering various effects.",
    "Alliance": "An ability word that triggers whenever another creature enters the battlefield under your control, providing various effects.",
    "Incubate": "A keyword action that creates an Incubator token with a specified number of +1/+1 counters, which can later be transformed into a creature.",
    "Pack tactics": "An ability word that triggers if you attack with creatures totaling power 6 or greater, granting various bonuses.",
    "Coven": "An ability word that provides effects if you control three or more creatures with different powers.",
    "Blitz": "A keyword ability that allows you to cast a creature for an alternative cost, granting it haste and causing it to be sacrificed at the beginning of the next end step, drawing a card upon death.",
    "Cleave": "A keyword ability that allows you to cast a spell for an alternative cost to ignore words in square brackets in its rules text.",
    "Boast": "An activated ability that can be used once each turn if the creature attacked that turn.",
    "Disturb": "A keyword ability that allows you to cast the backside of a double-faced card from your graveyard for its disturb cost.",
    "Bargain": "An ability word that provides additional effects if you sacrifice an artifact, enchantment, or token as you cast the spell.",
    "Adapt": "A keyword action that allows you to put +1/+1 counters on a creature if it has none.",
    "Toxic": "A keyword ability that causes a creature to deal both combat damage and poison counters equal to its toxic value.",
    "Start your engines!": "An ability word that provides effects when you activate vehicles or other machinery-themed cards.",
    "Venture into the dungeon": "A keyword action that allows you to progress through a dungeon, triggering room abilities.",
    "Training": "A keyword ability that puts a +1/+1 counter on a creature when it attacks alongside another creature with greater power.",
    "Vanishing": "A keyword ability that causes a permanent to enter with a set number of time counters, removing one each upkeep and sacrificing the permanent when none remain.",
    "Foretell": "A keyword ability that allows you to exile a card from your hand face down for 2 mana and cast it later for its foretell cost.",
    "Manifest dread": "An ability word that triggers when you manifest a card, providing additional effects.",
    "Support": "A keyword action that puts +1/+1 counters on each of up to X target creatures.",
    "Adamant": "An ability word that provides additional effects if at least three mana of a single color were spent to cast the spell.",
    "Delirium": "An ability word that provides effects if there are four or more card types among cards in your graveyard.",
    "Celebration": "An ability word that triggers if two or more nonland permanents entered the battlefield under your control this turn.",
    "Ascend": "A keyword ability that grants you the city's blessing if you control ten or more permanents, providing additional effects.",
    "Mutate": "A keyword ability that allows you to cast a creature spell for its mutate cost, merging it with a non-Human creature.",
    "Daybound": "A keyword that indicates a card transforms to its nightbound side if a player casts no spells during their own turn.",
    "Nightbound": "A keyword that indicates a card transforms to its daybound side if a player casts two or more spells during their own turn.",
    "Afterlife": "A keyword ability that creates a specified number of 1/1 white and black Spirit creature tokens with flying when the creature dies.",
    "Read Ahead": "An ability word that allows you to start a saga on any chapter, skipping earlier ones.",
    "Heroic": "An ability word that triggers whenever you cast a spell that targets the creature with heroic, providing various effects.",
    "Domain": "An ability word that provides effects based on the number of basic land types among lands you control.",
    "Spectacle": "A keyword ability that allows you to cast a spell for an alternative cost if an opponent lost life this turn.",
    "Converge": "An ability word that provides effects based on the number of colors of mana spent to cast the spell.",
    "Grandeur": "An ability word that allows you to discard a card with the same name as the creature to activate a special ability.",
    "Meld": "A keyword action that combines two specific cards into one oversized card with combined abilities.",
    "Buyback": "A keyword ability that allows you to pay an additional cost to return the spell to your hand upon resolution.",
    "Enlist": "A keyword ability that allows you to tap a non-attacking creature to add its power to the attacking creature's power.",
    "Casualty": "A keyword ability that allows you to sacrifice a creature with power N or greater to copy the spell.",
    "Fathomless descent": "An ability word that provides effects based on the number of permanent cards in your graveyard.",
    "Raid": "An ability word that provides effects if you attacked with a creature this turn.",
    "Endure": "An ability word that provides effects if you have taken damage this turn.",
    "Constellation": "An ability word that triggers whenever an enchantment enters the battlefield under your control.",
    "Plainscycling": "A keyword ability that allows you to pay a cost to discard the card and search your library for a Plains card.",
    "Amass": "A keyword action that creates a 0/0 Army creature token and puts a specified number of +1/+1 counters on it, or adds counters to an existing Army.",
    "Survival": "An ability word that provides effects if you have fewer cards in hand than an opponent.",
    "Backup": "A keyword ability that allows you to put +1/+1 counters on a creature and grant it abilities from the source card.",
    "Revolt": "An ability word that provides effects if a permanent you controlled left the battlefield this turn.",
    "Replicate": "A keyword ability that allows you to copy a spell for each time you pay its replicate cost.",
    "Max speed": "An ability word that provides effects if you control the creature with the highest power.",
    "Bloodrush": "A keyword ability that allows you to discard the card to give an attacking creature a temporary boost.",
    "Mountaincycling": "A keyword ability that allows you to pay a cost to discard the card and search your library for a Mountain card.",
    "Detain": "A keyword action that prevents a permanent from attacking, blocking, or activating abilities until your next turn.",
    "Fateful hour": "An ability word that provides effects if you have 5 or fewer life.",
    "Learn": "A keyword action that allows you to reveal a Lesson card from outside the game and put it into your hand or discard a card to draw a card.",
    "Craft": "An ability word that allows you to transform an artifact by exiling specified cards.",
    "Hellbent": "An ability word that provides effects if you have no cards in hand.",
    "Reinforce": "A keyword ability that allows you to discard the card to put +1/+1 counters on a creature.",
    "For Mirrodin!": "An ability word that creates a 2/2 red Rebel creature token and attaches the Equipment to it.",
    "Evolve": "A keyword ability that puts a +1/+1 counter on a creature when another creature with greater power or toughness enters the battlefield under your control.",
    "Swampcycling": "A keyword ability that allows you to pay a cost to discard the card and search your library for a Swamp card.",
    "Escalate": "A keyword ability that allows you to pay additional costs to choose more modes on a modal spell.",
    "Companion": "A keyword ability that allows you to designate a card as your companion if your deck meets certain conditions, allowing you to cast it from outside the game.",
    "Devour": "A keyword ability that allows you to sacrifice creatures as the creature enters the battlefield, putting +1/+1 counters on it for each sacrificed creature.",
    "Forestcycling": "A keyword ability that allows you to pay a cost to discard the card and search your library for a Forest card.",
    "Undergrowth": "An ability word that provides effects based on the number of creature cards in your graveyard.",
    "Impending": "An ability word that provides effects if a certain condition is about to be met.",
    "Spell mastery": "An ability word that provides effects if there are two or more instant and/or sorcery cards in your graveyard.",
    "Slivercycling": "A keyword ability that allows you to pay a cost to discard the card and search your library for a Sliver card.",
    "Splice": "A keyword ability that allows you to add the effects of one spell to another by paying its splice cost.",
    "Devoid": "A keyword ability that makes a card colorless, regardless of its mana cost.",
    "Emerge": "An alternative casting cost that allows you to sacrifice a creature and pay the emerge cost minus the sacrificed creature's mana value to cast a spell.",
    "Dash": "An alternative casting cost that gives the creature haste and returns it to its owner's hand at the beginning of the next end step.",
    "Morbid": "An ability word indicating that a spell or ability has an additional or alternative effect if a creature died earlier in the turn.",
    "Eminence": "An ability word that grants a benefit when your commander is in the command zone or on the battlefield.",
    "Swampwalk": "A form of landwalk; a creature with swampwalk is unblockable as long as the defending player controls a Swamp.",
    "Unleash": "You may have this creature enter the battlefield with a +1/+1 counter on it. It can't block as long as it has a +1/+1 counter on it.",
    "Islandcycling": "A variant of cycling that allows you to pay a cost to discard this card and search your library for an Island card.",
    "Level Up": "An activated ability that allows you to put level counters on a creature, unlocking new abilities or stats at certain levels.",
    "Forestwalk": "A form of landwalk; a creature with forestwalk is unblockable as long as the defending player controls a Forest.",
    "Skulk": "This creature can't be blocked by creatures with greater power.",
    "Jump-start": "You may cast this card from your graveyard by discarding a card in addition to paying its other costs. Then exile this card.",
    "Behold": "A keyword action that allows a player to choose a permanent they control of a particular quality or reveal a card of that quality from their hand, usually to pay a cost or get an additional effect.",
    "Sunburst": "This enters the battlefield with a +1/+1 counter on it for each color of mana spent to cast it.",
    "Ferocious": "An ability word that grants a bonus if you control a creature with power 4 or greater.",
    "Battalion": "An ability word that triggers when this creature and at least two other creatures attack, granting a bonus.",
    "Megamorph": "You may cast this card face down as a 2/2 creature for 3 mana. Turn it face up any time for its megamorph cost and put a +1/+1 counter on it.",
    "Strive": "You may pay an additional cost any number of times as you cast this spell to target additional creatures.",
    "Populate": "Create a token that's a copy of a creature token you control.",
    "Imprint": "An ability word indicating that a card exiles another card to grant additional effects.",
    "Decayed": "A creature with decayed can't block. When it attacks, sacrifice it at end of combat.",
    "Bolster": "Choose a creature with the least toughness among creatures you control and put a number of +1/+1 counters on it.",
    "Wizardcycling": "A variant of cycling that allows you to pay a cost to discard this card and search your library for a Wizard card.",
    "Embalm": "Exile this card from your graveyard: Create a token that's a copy of it, except it's a white Zombie with no mana cost. Embalm only as a sorcery.",
    "Undaunted": "This spell costs 1 less to cast for each opponent.",
    "Aftermath": "Cast this spell only from your graveyard. Then exile it.",
    "Formidable": "An ability word that grants a bonus if creatures you control have total power 8 or greater.",
}
